### ISSUE TITLE
Conflict with mod "Teleportation_Redux"

### ISSUE THREAD

**Issue by Santares** [Deadlock989/IndustrialRevolution#103]
**This mod has a conflict/ compatability issue with the mod "[Teleportation_Redux](https://mods.factorio.com/mod/Teleportation_Redux)"**
The game will give an error message at the launching page. The error message is "Error while loading entity prototype "IR-teleportation-portal-explosion" (explosion): Key"icon_size" not found in property tree at ROOT.explosion.IR-teleportation-portal-explosion" 

**Factorio version, IR version**
Factorio version: 1.1.70
IR version: 2.3.2

**Comment by Deadlock989** [comment]
This is a problem in Teleportation Redux. TR copies the entity gun-turret as the basis for making its teleportation portal entity. It then assumes that the turret has an icon definition rather than an icons definition like it does in vanilla, and replaces the icon and icon mipmaps parameters but not the icon size (lines 5-6 in TR's entity.lua). However if IR is installed, it has replaced the gun-turret icon definition with a completely legal icons definition. TR needs to account for the possibility that the entity it is copying has a legal icons definition and isn't a pristine untouched vanilla prototype.
