### ISSUE TITLE
Lazy Bastard achievement is impossible to get

### ISSUE THREAD

**Issue by ymgve** [Deadlock989/IndustrialRevolution#112]
The Lazy Bastard achievement can't be achieved in IR3 currently because the number of crafts required to get science up and running is too high for the default 111 craft number, even including the starting materials and scrap surrounding the teleporter. Maybe include a free 1x1 assembler or a steam science lab at the start of the game?

Factorio 1.1.74, IR 3.0.1

**Comment by Deadlock989** [comment]
Many of the cheevments are meaningless with IR3's changes and some are just plain broken. It was the same in IR2. I don't think they should exist in any modded game. I would disable them all, if even that wasn't made difficult by the achievement prototype structure. I may have a look at this at some point but motivation to spend any time on it is very low, sorry.

As a workaround you could opt to start in the copper age in map generation settings, this only ticks off three starter technologies and also provides you with assemblers.

**Comment by Deadlock989** [comment]
I did an audit of achievements.

- Solaris and Steam All The Way are broken by the addition of liquid petrochemical generators.
- Eco-Unfriendly is broken because IR uses its own custom oil processing technologies and the vanilla tech can't be unlocked.
- Iron Throne 1-3 are not technically broken but made pretty meaningless by IR's changes: ingots are the real measure of iron production and not plates. (The circuit production achievements are probably OK but the different costs of the three electronics tiers means the vanilla numbers required are pretty arbitrary.)
- Lazy Bastard is broken/unachievable if the default "stone age" map setting is used, and much more trivial than vanilla for all the other tech level "age" settings because assemblers are provided along with a bunch of other stuff you don't have to craft for yourself.

Motivation to fix these properly is very low because I'm just not interested in achievements, in Factorio or any other video game. Lazy Bastard is the only actually interesting one out of the whole lot. To be honest I would rather see it implemented as a different game mode where you can't handcraft anything and the starting conditions are different. Otherwise I don't want to give "stone age" players assemblers, bypassing Automation research, just to "fix" this one achievement. To fix it properly, someone needs to do a count of the minimum number of hand-crafts it takes to get Automation researched and a small steam assembler crafted, and that's not something I'm volunteering for.

My inclination at this point is still to disable the whole lot of them and let a third party mod fix them properly, if there's any desire on their part to do it.

**Comment by rlundy** [comment]
All of your reasoning makes sense, but it would be cool to have a "no hand-crafting" mode where a player starts out in stone age, but with enough items to bootstrap the rest without having to hand-craft anything.  In IR2 this was possible with the "starter kit" items.  I remember what you said about not wanting to have a different starter kit for each age.  Would it be less trouble to make this an age setting instead of a starter kit setting?  In addition to Stone Age there would be the starting age option of Stone Age (no hand-crafting), maybe?

**Comment by Deadlock989** [comment]
> Would it be less trouble to make this an age setting instead of a starter kit setting?

If you just mean, another "age" (Starting technology level) setting that hands out enough kit to fulfil the 111 hand crafts target set for vanilla, then that already exists - the "Copper" setting hands out labs and assemblers and a fairly small amount of logistics gear. It does also pre-research Automation, Logistics and Clockwork Construction techs, but those only cover the items which are handed out anyway - I don't like handing out kit that you can't already craft.

**Comment by Deadlock989** [comment]
I had one more look at this and decided it's not something I will ever find time for, so I have simply disabled the seven achievements mentioned above in the next version (will only affect new games). All a third party mod that wants to fix or expand achievements for IR3 has to do is set the `hidden` property on them back to nil or false and then make whatever other changes they see fit.

Regarding the idea of a full Lazy Bastard / No Handcrafting game mode, I think that is something best suited to an add-on mod because it would likely require start-up changes in any case (e.g. editing the default player character prototype). Such a mod could approach it as follows by depending on IR3 and then:

- Removing the default character crafting categories 
- Hiding the `ir-starting-age` setting 
- Using the provided `ir-world/set-crate-items` remote call to override starting gear, providing whatever is required to function without handcrafting

But this is not something I am likely to ever get around to doing.
