### ISSUE TITLE
Skip initial cutscene when loading debug world

### ISSUE THREAD

**Issue by raiguard** [Deadlock989/IndustrialRevolution#113]
**Describe the bug**
If you control+click the "single player" or "new game" buttons, the game will create a 50x50 freeplay world and will skip generating the crash site. It is very convenient for testing mods. IR3 continues to play the cutscene in the debug world, requiring me to wait for it to finish before I can start testing any changes that I've made. It would be awesome if IR3 could automatically disable the cutscene when the debug world is used.

Detect the debug world: `script.level.level_name == "freeplay"`, and the map dimensions are set to 50x50. I plan to add a new `debug_world` property to `script.level` to make the detection much less janky, but its addition is not a guarantee.

**Factorio version, IR version**
Factorio 1.1.74, IR 3.0.1

**Other mods installed**
None - the debug world is a hidden vanilla feature.

Fantastic job on IR3, it looks beautiful and I can't wait to play it!

**Comment by Deadlock989** [comment]
Gotta love hidden features.

I can think of two ways of handling this. 

One would be to disable the IR cutscene automatically for any world size below a threshold - it doesn't look great that the scene starts out in the void in any case.

The other would be to use the "freeplay" `get_skip_intro` interface call as the basis for IR's skip cutscene flag's default value - I'm assuming the control-click runs some script which uses those "freeplay" calls because it's returning true for the debug world. This would have the added advantage of creating some cross-compatibility with mods which are already using the "freeplay" call but don't know about IR's own call. The disadvantage would be that those mods would then have to explicitly enable the IR cutscene if for some reason they want that to stay but also want to explicitly cancel the vanilla scene (can't think why).

I'll think about it.

**Comment by Deadlock989** [comment]
I've gone with the latter - looking at freeplay script, it defines `is_debug()` as a surface called "nauvis" existing which is exactly 50x50, and sets its own skip_intro flag if that's the case. So in the next version IR3 will use freeplay's cutscene flag as the default basis for showing its own cutscene unless explicitly asked to do otherwise by an IR3 remote call.

**Comment by raiguard** [comment]
Ah, I didn't realize that the Freeplay script set that flag on the debug world. That's definitely a good solution! Thank you.
