### ISSUE TITLE
GUI close buttons missing hovered/clicked dark icon

### ISSUE THREAD

**Issue by tburrows13** [Deadlock989/IndustrialRevolution#114]
**Describe the bug**
For parity with vanilla GUIs, you should give your close buttons the the dark icon when hovered/clicked:

```
hovered_sprite = "utility/close_black",
clicked_sprite = "utility/close_black",
```

Obviously a minor complaint, it’s just because the rest of the mod is so polished and perfect… (well, except the lack of water reflections, but I can accept that is a lot of graphics work for minimal gain…!)

Thanks for the mod, I’m excited to try it out with Power Overload!

**Factorio version, IR version**
1.1.74, 3.0.1

**Comment by Deadlock989** [comment]
This will take a bit more than that for the transmat GUI because I didn't create black versions of the edit and map marker icons. (The core game doesn't seem to provide a 32x32 white edit icon - you can see how fuzzy it is on the train stop GUI - so I made my own and never noticed that highlighted buttons have a black sprite.)
