### ISSUE TITLE
IR3 config file for Resource Spawner Overhaul ore generation

### ISSUE THREAD

**Issue by MeHighTheGod** [Deadlock989/IndustrialRevolution#115]
**Describe the bug**
- On new game launch with IR3 3.0.1 and Resource Spawner Overhaul 6.2.21, 'tin-ore' and 'gold-ore' cannot be found in config file and it's not spawned in the world.

**Factorio version, IR version**
Factorio 1.1.74 (build 60256, win64)
IR3 3.0.1

**Other mods installed**
Resource Spawner Overhaul 6.2.21

**Comment by Deadlock989** [comment]
This is most likely because the internal mod name has changed (from "IndustrialRevolution" to "IndustrialRevolution3"). There is nothing I can do about this from my end - if you want RSO updated, you should ask orzelek if he can copy the IR2 config over to IR3, tin and gold ore quantities have not changed significantly since the IR2 config was made.
