### ISSUE TITLE
alt mode & hover mode on the steam derrick overlap

### ISSUE THREAD

**Issue by Quezler** [Deadlock989/IndustrialRevolution#118]
**Describe the bug**

not sure if its just overlapping or also dimensions since transparency stacking confused the eyes, but it looks weird:
https://user-images.githubusercontent.com/3179271/209530955-1bd26e3d-658a-42e4-9f6f-98546a5aef7c.mov
and yes i am aware this might (and probably is) an issue with factorio itself & not directly the cause of IR3 ^-^

**Factorio version, IR version**
1.1.74 & 3.0.1

**Other mods installed**
![Screenshot 2022-12-26 at 10 21 59](https://user-images.githubusercontent.com/3179271/209531164-70523220-e992-4c7b-a7a3-d40eb13236e2.png)

**Comment by Deadlock989** [comment]
This appears to be a vanilla issue with the fluidboxes on drill entities because exactly the same thing happens on pumpjacks (which IR3 hasn't touched except for energy source and health properties). There are several other weird and inconsistent issues in the core game around fluidbox filter icons, I have reported a few.
