### ISSUE TITLE
IR3 and SqueakThrough mod fix

### ISSUE THREAD

**Issue by Astorin** [Deadlock989/IndustrialRevolution#119]
**Describe the bug**
When loading IR3 together with SqueakThrough mod there is an error:
`Error ModManager.cpp:1560: Error while loading entity prototype "steel-vaporiser" (furnace): Invalid pipe connections specification for offset {-1.2500000000, 0.0000000000}. The offset must be outside of the entity bounding-box
Modifications: Industrial Revolution 3 › Squeak Through › Industrial Revolution 3`

**Factorio version, IR version**
Factorio 1.1.74 stable, IR 3.0.1

**Other mods installed**
SqueakThrough 1.8.2

After qiuck investigation I found a solution:
Edit 2 values in the file
IndustrialRevolution3_3.0.1\code\entities\entities-fluid.lua 

Section "vaporiser.fluid_boxes":
Line 938: change value -1.25 to -1
Line 947: change value 1.25 to 1

And that's all, IR3 and SqueakThrough works fine together.

**Comment by Deadlock989** [comment]
No, I need those values to be as they are so that the different alt-mode fluidbox filter icons do not overlap.

Squeak Through should not be changing entity collision boxes to illegal values - the base game requires fluidbox positions to be within the entity's bounding box and ST is breaking that hard restriction without checking.

**Comment by Astorin** [comment]
But with my fix suggestion fluid input icons overlapping very nice:
[Comparison before and after fix](https://imgur.com/Wuh48mb)

**Comment by DarkShadow44** [comment]
@Astorin Just report the issue to Squeak Through, it's their code that messes things up.
