### ISSUE TITLE
DeadlockLargerLamp not compatible with AfraidOfTheDark

### ISSUE THREAD

**Issue by Daschi1** [Deadlock989/IndustrialRevolution#127]
I couldn't find an issue tracker for DeadlockLargerLamp, so I am posting this here.

**Describe the bug**
I have AfraidOfTheDark and DeadlockLargerLamp enabled at the same time, but it throws an error when loading the game:
![image](https://user-images.githubusercontent.com/50054971/209661167-94a2b5aa-5ae8-4ad6-9ffe-6fae6de2085f.png)

**Factorio version, IR version**
Factorio: 1.1.74
DeadlockLargerLamp: 1.5.0
AfraidOfTheDark: 1.1.1

**Other mods installed**
I disabled all my other mods one by one, they all work with DeadlockLargerLamp, but as soon as AfraidOfTheDark is enabled the game won't load.

**Comment by Deadlock989** [comment]
This issue is being caused by Afraid of the Dark, which is changing the fast_replaceable_group of every lamp it can find in the game (its own lamps, vanilla's, and any other mod-created lamp) at the last possible moment. Copper lamps are technically not real lamps but a kind of furnace, so they are being missed. The base game does not require entities with a next_upgrade_target to be of the same entity type, but it does enforce that they must both be in the same fast_replaceable_group, so in this case AOTD is breaking that hard requirement, producing the error. It also shouldn't be putting the DLL lamps into the same group as small lamps in the first place, that's also likely to cause issues.

Unfortunately there is very little I can do about this.
