### ISSUE TITLE
with a few mods it broke.

### ISSUE THREAD

**Issue by SGZ-Creations** [Deadlock989/IndustrialRevolution#128]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59801736/209662512-d461db2c-d8f6-473d-86bd-bdf694ef0461.png)
Adding the mods and confirm the crash happens on first load. With listed mods.

**Factorio version, IR version**
IR 3.0.3
![image](https://user-images.githubusercontent.com/59801736/209662018-cc1f3005-8e16-42b5-878f-73218b8ebddb.png)
![image](https://user-images.githubusercontent.com/59801736/209662381-128d7709-1448-4e9e-8b88-39801820817a.png)

**Other mods installed**
https://mods.factorio.com/mod/auto-research
https://mods.factorio.com/mod/BigBags
https://mods.factorio.com/mod/blueprint-sandboxes
https://mods.factorio.com/mod/Configurable-Armour-Suits
https://mods.factorio.com/mod/creative-mod
https://mods.factorio.com/mod/flib
https://mods.factorio.com/mod/Infinizoom
https://mods.factorio.com/mod/LoaderRedux

**Comment by SGZ-Creations** [comment]
Issue cased by loader redux

**Comment by Deadlock989** [comment]
This is probably because IR3 enforces hard dependencies in the technology tree (all ingredients for recipes unlocked by a technology must already have been unlocked), and Loader Redux is putting an item with iron components (I'm guessing the loader) into a technology that in IR3 is prerequisite for unlocking iron, creating a cycle.

This is a mod conflict which requires work on someone's part to resolve - unfortunately that person isn't me at this time.
