### ISSUE TITLE
Steam inserters upgrade to the wrong items in upgrade planner

### ISSUE THREAD

**Issue by IdahoEv** [Deadlock989/IndustrialRevolution#13]
Issue: in upgrade planner, suggested upgrades for steam inserters are not valid upgrades.

Expected behavior: steam inserters should be upgradable to electric inserters, fast inserters, and/or stack inserters
Actual behavior: steam inserters upgrade to long-handled steam inserters and to etheric lamps (!)

To Reproduce: 
  1) create an upgrade planner
  2) click on a left column, select steam inserter
  3) click on cell to the right of the steam inserter.   Observe that the only selectable items are long-handled steam inserter and etheric lamp
  
(Similarly, long-handled steam inserters "upgrade" to steam inserters and etheric lamps, instead of long-handled electric inserters)

Thanks for creating such a great mod!

**Comment by IdahoEv** [comment]
steam inserter in left cell:
![image](https://user-images.githubusercontent.com/440321/107708812-5d7d3600-6c81-11eb-84d4-edbe6363fcfc.png)

long-handled steam inserter and etheric lamps only selectable options in right cell:
![image](https://user-images.githubusercontent.com/440321/107708865-74bc2380-6c81-11eb-88da-817757944129.png)

**Comment by Deadlock989** [comment]
Unfortunately this is one of those things where there is no ideal solution. Upgrades have a hardcoded association with "fast replace groups" (FRGs). Things can only be upgraded to each other if they are in the same FRG and they have the same collision box.

In vanilla, all inserters are in the same FRG, except long-handed inserters, which are in a group on their own. In IR2, steam inserters (and long-handed steam inserters) are currently in the same FRG as pipes, because I felt it was 100x more common to want to fast-replace a steam pipe with a steam inserter (or replace a misplaced steam inserter with a pipe) than to need to fast-replace a steam inserter with an electric inserter. This is why aetheric lamps appear as a potential upgrade, because they are also very pipe-like. (Pipes don't appear because they have a different collision box which can't be changed without additional mayhem.) 

I could put steam inserters in the same FRG as the other inserters, but then you would not be able to fast-replace a pipe with a steam inserter any more. Also, it would allow you to "upgrade" e.g. a filter stack inserter into a steam inserter, which is not something I would expect anyone would evert want to do, realistically. So while it doesn't make much sense in the context of the upgrade planner menu, I don't think there is much I can do about that without making manual placement of steam inserters more limited. I think there is more value in having them fast-replace pipes than in having them be upgradeable to electric inserters. You would still need to clear away all the piping in an electric set-up anyway.

I will leave this issue open for now in case I have a brainwave or can be persuaded otherwise but currently I think this is the best compromise.

**Comment by IdahoEv** [comment]
That makes complete sense.   I can confirm that I have fast-replaced steam pipes with inserters many, many times.

Might be worth filing a feature request with the game, though I have no idea how big a deal it would be under the hood to allow a more complex set of relationships.

**Comment by Deadlock989** [comment]
Closing for now, pending any future API updates that allow for more fine-grained control (unlikely).
