### ISSUE TITLE
Bottomless pit missing recipe in 3.0.3

### ISSUE THREAD

**Issue by chi-feng** [Deadlock989/IndustrialRevolution#130]
**Describe the bug**
I enabled the bottomless pit in the map settings, but there is no longer a crafting recipe for it. Earlier in version 3.0.1 I remember seeing the crafting recipe. 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/336681/209734985-5c1e1579-e92e-4cd2-9379-0c167395385f.png">

<img width="621" alt="image" src="https://user-images.githubusercontent.com/336681/209736355-a5985ab2-95dd-43a7-993b-649f487cb60b.png">

**Factorio version, IR version**
Factorio 1.1.74 IR 3.0.3

**Other mods installed**
Mod list:
```
base
chest-auto-sort
CursorEnhancements
DeadlockBlackRubberBelts
DeadlockLargerLamp
factoryplanner
flib
IndustrialRevolution3
IndustrialRevolution3Assets1
IndustrialRevolution3Assets2
IndustrialRevolution3Assets3
IndustrialRevolution3Assets4
Milestones
ModuleInserter
PipeVisualizer
RecipeBook
stdlib
```

**Comment by Deadlock989** [comment]
I think this is being caused by the mod's migration script calling `reset_technology_effects()`, which is documented as only refreshing "research effects" but also seems to be clearing the enabled status of recipes not actually unlocked by any technology (e.g. the bottomless pit), which I didn't expect.

If you don't care about losing achievements you can unlock it again with the following command:

`/c game.player.force.recipes["bottomless-pit"].enabled = true`

I will have to have a think about to handle this differently.

**Comment by Deadlock989** [comment]
This is fixed for the next version but required some changes.

- In 3.0.4 it will be possible to change the setting mid-game. In multiplayer this can only be done by admins.
- The setting will also be checked/refreshed on mod config change and version update, and also if the `force.reset_technology_effects()` function is called from the console or by some other mod.
