### ISSUE TITLE
Missing rubber trees

### ISSUE THREAD

**Issue by darthmat** [Deadlock989/IndustrialRevolution#133]
**Describe the bug**
Creating a new map with max starting area size, move rubber trees very very far outside of starting position. When i preview a new map i even don't see any on it. Seems like it shouldn't be depent of starting area that should only affect bugs nest? Or maybe its on purpose because rubber is like more middle/end game stuff?

**Factorio version, IR version**
Factorio: 1.1.74
IR3: 3.0.3

**Comment by Deadlock989** [comment]
This is very tricky to balance right.

The base game mostly uses the "starting area" concept to block biter spawning within a radius from the starting point, as you say. But it does also use it to define the patch where special starting ores are spawned. Trees use the same "autoplace" system as ores, so if I want to exclude them from the starting area (because otherwise they would spawn all around the starting area water patch and it would be trivially easy to get hold of them), this means the starting area size slider also affects them. If there is a way of controlling that in more detail, I don't know what it is.

It's also extremely weird to me that you can dial up the starting area size to maximum and then turn off biters, which disables the starting area slider (as if it were now meaningless) but still uses whatever value it had before within the game itself, affecting both rubber trees and gem rocks.

If you can give me examples of map exchange strings where you would expect to see rubber trees I can take another look but otherwise my feeling is that by making the difficulty easier by banishing biters out to 600% (in game this is a circle with 1.8km diameter!) you will also have to put up with the 10 minute task of taking a monowheel trip out to wetter ground.

**Comment by darthmat** [comment]
If you want to look through, here is a map string:
`>>>eNpjZGBk8AJiIGiwX71Ky46bJTk/MWf1qlV2DAwHHECYKzm/oCC1
SDe/KBVZmDO5qDQlVTc/E1Vxal5qbqVuUmJxKshEGOZIz89JQTeBP7N
It6g0KQlodklRamoxiobMovw8dA2sxSX5eSgi7CWZmKowDOMuLUrMyy
zNRVfJwLj0daxnQ4scAwj/r2dQ+P8fhIGsB8AAAWEGxgaQSkZGoBgMs
CbnZKalMTAoOAKxE0SMEULpOUBZB5IcoEKeeIQYTIAsYzD4bI9gVIus
c39YVWLPCFPG4YBgQCRb7KEiDIxMcGLWTBDYCZeC6XpgD5W6ac949gw
IvLEHaxXgAxILeoCEggzcD3YwbSIOjGlg8A3mtscwxmV7dJepODDagI
yUAxEnQAQrIliALmGEMB36HRgd5GGykgglQP1GDMhuSEH46CTM2sNI9
qM5RMUBHqRY/IEmouKAJWC5QBamwIkXzHDXAMPvAjuM5zDfgZEZxACp
+gIUg/BAMjCjILSAA6MIkGJmQIAP9gzXDjaJAACyy65h<<<`

but if you said its quite tricky, then just probably a trip is what i can do :)

**Comment by Deadlock989** [comment]
I did some reading just now and found something I missed for the previous couple of years. It looks like it might be possible to exclude rubber from the world centre without having that exclusion zone tied to starting area size. Fiddling with it now, but with your map string above it already looks promising.

**Comment by Deadlock989** [comment]
Your map settings in the string above were also disadvantaging you slightly because you have water coverage turned down really low, and the edges of lakes are used by the spawn weighting to make rubber trees in appear on terrain where they usually wouldn't, e.g. dry and/or cold areas. So it was almost the worst case scenario: few lakes, pretty dry map, maximum starting area size.

Anyway I'm happy with the new method, which uses a fixed distance from centre instead of starting area size. For your string above, which is not far from as the worst that RNGesus might hand you, you get some decent sized rubber tree clumps within the map preview picture using this method, without having to change the rubber tree scale or coverage sliders. 

This will be included in the next version (3.0.4).

**Comment by AndrewD22** [comment]
anyway to fix on existing map? I've explored way out and not a single rubber tree found.
My wood settings are default, but upper grass bias a little. biters set to 400% of starting area.
[https://ibb.co/Fsb4Cc2](https://ibb.co/Fsb4Cc2)

**Comment by AndrewD22** [comment]
could some other mod overwrite rubber tree generation? started new map with all default settings and still didn't find any rubber trees within few hundred chunks of starting area.

**Comment by Deadlock989** [comment]
> could some other mod overwrite rubber tree generation? started new map with all default settings and still didn't find any rubber trees within few hundred chunks of starting area.

It is starting to look like there is something interfering, yes. Can you please list the mods you have installed, and also give me the map exchange string for the screenshot you posted above? Thanks.

**Comment by AndrewD22** [comment]
exchange string for the screenshot map:
>>>eNpjZGBk8AJiIGiwB2FuluT8xBwI7wAYcyXnFxSkFunmF6UiC3Mm
F5WmpOrmZ0IVMzgAkQNXal5qbqVuUmJxKsxEEOZIz89JQTeBP7NIt6g
0KQlodklRamoxiobMovw8dA2sxSX5eSgi7CWZmKowDOMuLUrMyyzNRV
fJwCjTkb2noUWOAYT/1zMo/P8PwkDWA6CHQJiBsQGow4GBESgGBYyyy
fl5JUX5ObrFqSVA+9OtcvMzi0tKi1KtkjITizkM9IwNQIA1OSczLY2B
QcERiJ3AOhkZq0XWuT+smmLPCDFLzwHK+AAVOZAEE/GEMfwccEqpwBg
mSOYYg8FnJAbE0hKgFVBVHA4IBkSyBSTJyNj7duuC78cu2DH+Wfnxkm
9Sgj2joavIuw9G6+yAkuwgLzDBiVkzQWAnzCsMMDMf2EOlbtoznj0DA
m/sGVlBOkRAhIMFkDjgzczAKMAHZC3oARIKMgwwp9nBjBFxYEwDg28w
nzyGMS7bo/sDGBA2IMPlQMQJEAG2EO4yRgjTod+B0UEeJiuJUALUb8S
A7IYUhA9Pwqw9jGQ/mkMwIwLZH2giKg5YooELZGEKnHjBDHcNMDwvsM
N4DvMdGJlBDJCqL0AxCA+S/SBGQWgBB3Bww2QhaYPhR2vSfwD1tMQZ<
<<

**Comment by AndrewD22** [comment]
mods:
miniloader
aai-containers
actual craft time
additional paste settings
automatic underground pipe connectors
blueprint flip and turn
bottleneck
colorbindcircuitnetwork
deadlockblackrubberbelts
even-distribution
extended-descriptions
factorysearch
far-reach
fill4me
fnei
inbuilt_lighting
informatron
inserter-throughput
isnerter_config
kux-zooming
maxratecalculator
power armor mk3
qol_research
resourceMarker
stdlib
stonewaterwell
vehiclesnap
factoryplanner
moduleinserter
pickerdollies
gui_modifier
industrialrevolution-miniloader (I modified this one to be compatible with IR3)

**Comment by Deadlock989** [comment]
Thanks. So I can rule out any third party mod. It's just that your 400% starting area size equated to an exclusion zone radius of 600m. There are some large patches of rubber trees just outside the area you have explored to the east, and more (without any biters nearby) on the lake shore to the northwest, and more just to the west of the large oil patch on the very edge of your explored area to the south. If you load up the map exchange screen from a new single player game screen and fiddle with the starting area size down to 200% or 150%, you'll start to see rubber trees appearing within the preview screen area.

This won't be an issue in 3.0.4 onwards after the rubber tree exclusion zone has been made independent from starting size area. I don't have a way to regenerate any trees in existing chunks but any new chunks explored in existing games will start to generate using the new autoplace method.

**Comment by AndrewD22** [comment]
thanks for looking into this.
