### ISSUE TITLE
Entity adjustment hotkey active even when hand not empty

### ISSUE THREAD

**Issue by b-jonas0** [Deadlock989/IndustrialRevolution#137]
**Describe the bug**
I would like to bind the IR3 entity adjustment hotkey to the same key as the increase tile size and flip blueprint hotkeys.  This doesn't seem to work, if I bind the IR3 entity adjustment hotkey then the other two functions don't work.  The entity adjustment hotkey should eat the command only if the hand is empty and my cursor is over a building to which that command applies, such as a constant combinator.  It could perhaps also eat the command if I have a building like the aetheric lamp in my hand that can be adjusted before I place it.  

I use such a binding outside of IR3 and multiple mods handle this well: I use the same key to increase tile size (when I'm holding a tile), flip blueprint (when I'm holding a blueprint), permute fluid inputs (with https://mods.factorio.com/mod/fluid_permutations , when hovering over a refinery or chemical plant), change direction of an  underground pipe connector (with https://mods.factorio.com/mod/pipelayer , when hovering over a pipe connector), decrease sync delay of a Factorissimo connection (with https://mods.factorio.com/mod/factorissimo-2-notnotmelon , when hovering over a pipe/chest/heat connector in a Factorissimo factory building wall), toggling a constant combinator (with https://mods.factorio.com/mod/combinator-toggle , when hovering over a constant combinator), all in a single game.  For some of these mods, the hotkey still affects a building that I'm hovering over even when I'm holding an item or tile, which may be a bug, but they at least don't block the other functions from working at all, which is why I think IR3 should be able to do this as well.

**Factorio version, IR version**
I'm running Factorio 1.1.74 (build 60256, linux64) with Industrial Revolution 3 version 3.0.4.

**Comment by Deadlock989** [comment]
This is happening because the custom input for the hotkey is currently set to block/consume game events, i.e. game engine functions that also have an associated hotkey. There may have been a reason for this, or not; if there was, I can't remember it. It will be changed in the next version to not block game events.

However assigning a conflicting keybinding in this way introduces another minor issue. Currently the mod also listens for the increase/decrease tile size game input event to cycle through the recipe colours that aetherics lamps use if you are also highlighting one. This isn't a custom input event as such but a linked game control event, meaning it can't be bound to other keys independently from the tile size event. So binding the toggle hotkey to the same key as either of the tile size adjustment keys will effectively prevent you from being able to cycle the colours in that direction. This isn't critical as you can also change the aetheric lamp's colour by opening the machine's gui. I don't want to remove the functionality but I'm not going to introduce two separate new keybindings just for this very minor function alone.

> The entity adjustment hotkey should eat the command only if the hand is empty and my cursor is over a building to which that command applies

Unfortunately this isn't possible with the current game engine as far as I know. Custom inputs can either consume game events or not, it can't be done conditionally.

> It could perhaps also eat the command if I have a building like the aetheric lamp in my hand that can be adjusted before I place it.

Also not possible, at least with the way the toggle hotkey currently works. There is no separate placeable item for the entity variants so there is nothing that can be done with the item in the cursor stack; even if there were, you can't conditionally consume custom inputs, as above.

> For some of these mods, the hotkey still affects a building that I'm hovering over even when I'm holding an item or tile, which may be a bug

I don't think this is a bug. For example the built-in "connect rolling stock" game input event still works when you have a tile in your hand.

**Comment by b-jonas0** [comment]
> It will be changed in the next version to not block game events.

Thank you.  Inspired by this bug report, I rethought my keybindings. I changed the binding for increase/decrease tile size to 'V' and 'C', which I also use for blueprint book next/previous.  This helps even with the other mods, because with increase/decrease tiles bound to 'G' I could accidentally adjust an entity while increasing tile size with a tile in my hand, which could cause mysterious bugs in my chemical setups.   

I will keep flip blueprint on the same key 'G' as all the other mod functions for now, since that does not seem to conflict: if I have a blueprint in my hand and press 'G', none of the modded functions that affect an entity seem to activate. I expect that after you make this change to IR, I will be able to use that same hotkey for the IR adjust entity function too. Even this makes me a bit uneasy, I'll consider to rebind flip blueprint to some other key so that 'G' only does functions that affect the entity under my cursor. 

> I don't think this is a bug. For example the built-in "connect rolling stock" game input event still works when you have a tile in your hand.

The opposite example are the rotate and reverse rotate keys.  Factorio makes these affect the item in your hand if you have one, but the entity under your cursor if you don't.  All the mouse buttons and shifted and controlled mouse buttons also have different functions if you have an item in your hand or not, as well as the empty hand or pipette key in the default bindings.  But rotate and reverse rotate are notable because Factorio doesn't even let you bind the hand and entity functions to separate keys even if you want to.  It's because of these key and mouse functions why I was hoping I could overload 'G' this way, but now I see that the mod API doesn't let me do this.
