### ISSUE TITLE
Incompatible with Beacon Overhaul

### ISSUE THREAD

**Issue by nekopsykose** [Deadlock989/IndustrialRevolution#138]
**Describe the bug**
loading both beacon overhaul and IR3 yields the following traceback at map start (landing? first frame of the game starting):

![traceback](https://img.ayaya.dev/OZ5o385BJbLA)

(apologies for the image, couldn't copy the text for some reason)

i also reported this to beacon overhaul- not sure what specifically breaks this.

**Factorio version, IR version**
3.0.4 IR3, 1.1.74 Factorio

**Other mods installed**
reproduced with just IR3+beacon overhaul

thanks for the work on IR3!

**Comment by Deadlock989** [comment]
This looks like a mistake in BO to me - its `on_entity_cloned` event is calling a function which checks for `event.entity` or `event.created_entity` but neither of those is passed back by `on_entity_cloned`, which uses `event.source` and `event.destination` instead, so the script crashes when it tries to index nil.

I am motivated to have BO compatible with IR3 because I like the concept, so if there are other compatibility issues with this specific mod please report them, but I don't think there is anything I can do in this case.

**Comment by nekopsykose** [comment]
right, makes sense. thanks for the fast response!

**Comment by Deadlock989** [comment]
This might be an alternative, I haven't tested it however.

https://mods.factorio.com/mod/wret-beacon-rebalance-mod

**Comment by Deadlock989** [comment]
IR3 will internally support wretclaw120's mod in version 3.0.5 (recipe/tech prereq changes).

**Comment by nekopsykose** [comment]
> In fact it appears that this mod was based on notnotmelon's and fixed the same bug as the one you report well over a year ago:

oh, awesome. i guess i'll use that instead :)

> IR3 will internally support wretclaw120's mod in version 3.0.5 (recipe/tech prereq changes).  

even better! thanks for the hard work, as always. <3
