### ISSUE TITLE
Endgame description?

### ISSUE THREAD

**Issue by aeosynth** [Deadlock989/IndustrialRevolution#143]
Hi, I'd like to see in the mod page some details about the endgame, is the goal the same as vanilla, launch a single rocket? I realize this might be spoiler territory.

**Comment by Deadlock989** [comment]
The mod is built on vanilla Factoro, i.e. is an overhaul of vanilla Factorio - there's a list of things that are different so it's safe to assume that if I haven't mentioned it, it isn't particularly different. Rocket launches require different ingredients to vanilla but otherwise it's the same mechanic.
