### ISSUE TITLE
Assembler tier related incompatibility

### ISSUE THREAD

**Issue by TheBlueChocolate** [Deadlock989/IndustrialRevolution#154]
**Describe the bug**
When trying to play with IR3 and amator phasma's nuclear, the non machines recipes that are available in a tier 1 vanilla
assembler are unavailable, while those available from tier 2 vanilla assemblers are still available.

On the picture bellow, the left crafts are from a tier 2/3 vanilla assembler, the middle ones from a tier 1 vanilla assembler, and the right one, any of the three "standard" IR assemblers.

![2023-01-06_01h39_31](https://user-images.githubusercontent.com/33001303/210916515-b6861bba-5bb9-46e0-a368-05d0b7a365dd.png)

When looking at these recipes in the inventory, it doesn't know where to craft it:

![2023-01-06_03h28_16](https://user-images.githubusercontent.com/33001303/210917613-2121a3da-9bd6-4179-8c3a-a104d634ae9d.png)

**Factorio version, IR version**
1.1.74, 3.0.7

**Other mods installed**
Amator Phasma's Nuclear (forked)
Realistic Reactors

**Comment by Deadlock989** [comment]
This is happening because IR3 does not make use of vanilla's "advanced-crafting" recipe category, which is only used once in the entire vanilla game (to craft engine units, because obviously it's normal to assemble an entire oil refinery from things found in your pocket but it would be ludicrous to attempt a lawnmower engine). APN uses the category for many of its intermediates.

Since this issue is rooted in a vanilla game feature, I have fixed it for the next version (electric and advanced assemblers will support the "advanced-crafting" category). However the "AP forked" series of mods are not likely to be supported by me if further issues (not related to vanilla game features) arise.
