### ISSUE TITLE
[Compatibility] Blacklist omnimatter instead of omnilib

### ISSUE THREAD

**Issue by Cereal-Sam** [Deadlock989/IndustrialRevolution#155]
Hi,

currently IR3 blacklists omnilib which means that no omni mod can be used with IR3 at all.
It would be great if you could blacklist omnimatter instead of omnilib.

Why?
We have qol / non-content mods that work out of the box with IR3 that are only dependant on omnilib.
All our content-adding mods are dependant on omnimatter. Blocking omnimatter means that no omni-content mod can be used.

Mod to blacklist instead of omnilib:
https://mods.factorio.com/mod/omnimatter

**Comment by Deadlock989** [comment]
I was very reluctant to do this, due to past experiences with that library and the mods which use it. But it has been a couple of years since I last tangled with them so I took a look at two of the mods which don't require Omnimatter.

Omnipermute+IR3 does get to the main menu, but it deletes any previously researched fluid recipe if the mod is introduced mid-game, putting the saved game into a broken state. Techs as simple as heavy oil processing now produce 12 different recipes instead of 1, I guess this is exactly what was intended, but it's not my cup of tea, in fact, it's not even a cup, or tea. Crucially however it completely wrecks the advanced forestry fertilised wood growth scripts by destroying the recipes that IR3 creates for that purpose, generating a script crash the moment you try and place an advanced forestry or when the forestry cycle ticks over in an existing save. 

Omnifluid+IR3 fails to load, giving this error:
```
   2.388 Script @__omnimatter_fluid__/prototypes/sluids-generation.lua:265: This should be empty
   2.388 Script @__omnimatter_fluid__/prototypes/sluids-generation.lua:266: dirty-steam
   2.388 Script @__omnimatter_fluid__/prototypes/sluids-generation.lua:267: {
  {
    temp_min = 200
  }
}
   2.388 Script @__omnimatter_fluid__/prototypes/sluids-generation.lua:268: {
  "none"
}
   2.388 Script @__omnimatter_fluid__/prototypes/sluids-generation.lua:269: "Min: 15 Max: 1000"
   2.391 Error ModManager.cpp:1560: Failed to load mod "omnimatter_fluid": __omnimatter_fluid__/prototypes/sluids-generation.lua:483: attempt to index local 'new_item' (a nil value)
stack traceback:
	__omnimatter_fluid__/prototypes/sluids-generation.lua:483: in main chunk
	[C]: in function 'require'
	__omnimatter_fluid__/data-final-fixes.lua:13: in main chunk
```

Sorry, but I don't see any upsides to this.

**Comment by Cereal-Sam** [comment]
Thanks for the feedback.
I know that there might be some work on my side regarding some exceptions like the permutation one that you mentioned.
The omnifluid crash is definetly a bug on my side as well, i will fix that with the next update.

I did not check / add any compat yet to not waste time for the case that you keep the blacklist, but it would be great if you let me know if that could work out for you.


> I was very reluctant to do this, due to past experiences with that library and the mods which use it. But it has been a couple of years since I last tangled with them so I took a look at two of the mods which don't require Omnimatter.

Yeah, the code was in a pretty bad state before we started maintaining it. It crashed with pretty much anything outside of default AngelsBobs :)
