### ISSUE TITLE
Explosives analysis pack order incorrect

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#161]
**Describe the bug**
The explosives analysis pack has it order set so that it is after the electrum analysis pack. Based on when it is unlocked it should be after the steel or iron analysis pack.

**Factorio version, IR version**
   0.396 Loading mod base 1.1.74 (data.lua)
   0.608 Loading mod IndustrialRevolution3 3.0.8 (data.lua)

**Comment by Deadlock989** [comment]
This is working as intended - explosives/military pack is a different type of pack that has different properties (i.e. it doesn't chain).

**Comment by Bilka2** [comment]
Is it also intended that this effects the order of technologies in the tech list?
![Screenshot_20230108_163713](https://user-images.githubusercontent.com/27060268/211205426-07d77b58-50fd-4bcc-bd26-5e64c579afd5.png)

As far as I know, the list is ordered based on the item order and tech cost.

**Comment by Deadlock989** [comment]
That isn't solvable as far as I can tell. The fact that the order property of technology prototypes seems to be completely ignored by that list (I'm not even sure what technology.order is for), in favour of what I'm guessing is the concatenated order strings of the tool prototypes used to research the tech followed by the unit cost if that order is equal, creates all kinds of weirdness unless you've structured your tree in exactly the way that vanilla does. 

I just wasted an hour getting IR3 to automatically calculate tech and analysis pack order based on the tree depth of the tech that unlocks the pack: if nothing else interferes, this puts explosives packs in between the steel and chrome packs. That results in completely broken orders like this:

![image](https://user-images.githubusercontent.com/3128845/211325031-34b8dc23-cfb5-4f20-9b5a-ae505989640b.png)

Personal arc turret: copper-iron-steel-chrome, cost 1100, tree depth 22
Military 3: copper-iron-steel-explosives-chrome, cost 600, tree depth 17
Arc furnaces: copper-iron-steel-chrome-electrum, cost 1000, tree depth 21

These shenanigans are multiplied with the work-in-progress IR3SP add-on installed because that mods adds a further 10 packs but some are extremely expensive and the unit cost is very low and unit time very high to compensate, so there is literally no way of ordering the techs in any satisfying way.

If the base game provides some other tool for overriding this list's order I will look at this again.
