### ISSUE TITLE
no wood gasification recipe for wood crushing

### ISSUE THREAD

**Issue by GoldHeartTheOne** [Deadlock989/IndustrialRevolution#164]
Hi, with the recipe for creating rubber it crates a byproduct of wood crushing which currently the only use is to make charcoal which isnt very useful unless you have a very big wood farm, so I thought about making gas from the wood crushing but theres no recipe for wood gasification.

do you have any plans on adding a recipe to for wood crushing gasification?

P.S. I know this is the bug report area I just didnt know where else to post this issue. 
I hope to hear from you soon!

Factorio: 1.1.74
IR3: 3.0.8

**Comment by Deadlock989** [comment]
Wood chips are the primary source for ethanol (Ethanol 1 tech) which is useful in the mid-game and essential in the late game. In development there were other gasification recipes, including ones for wood chips and charcoal, but in practice any excess natural gas was also being used to make ethanol (Ethanol 2 tech) so they were removed because they were basically redundant and inefficient.

**Comment by GoldHeartTheOne** [comment]
thanks for the replay, sorry I didnt know that. 

have a good day!
