### ISSUE TITLE
[Feature request] Electrolyzer

### ISSUE THREAD

**Issue by tabr** [Deadlock989/IndustrialRevolution#166]
So. It seems to be must be...
Because produce H2 from... Nature gas only? And O2 from... Air(and trees - endgame) only?
There is lot amount of water!
Also there is a lot of electricity that has no place to use.
Or i don't know something?
Also would be awesome reaction: CO2 => O2 + coal...

**Comment by Deadlock989** [comment]
Short answer: I would like to do this but there are reasons why it's not practical.

Long answer:

Electrolysis of water was explored during development and there is even an icon available for the recipe. However it was not included for the following reasons.

The reason we don't use water electrolysis as a primary source of hydrogen in the real world is because it is very inefficient compared to obtaining hydrogen from fossil fuels and biomatter. The best electrolysis processes might produce hydrogen worth about 80% of the energy put in. In terms of game design, I am happy with that, because water is infinite and if electrolysis had 1:1 or higher energy efficiency then electricity would also be infinite. However, it means that electrolysis is even more expensive.

The real problem is that there is no suitable building available. The only currently appropriate building that can take in one fluid input (water) and produce two fluid outputs (hydrogen and oxygen) is the vanilla chemical plant. The issue is that the chemical plant's power input is very low and the energy value of hydrogen is very high. At 125 kW, with 80% efficiency, it would take about 13 seconds just to get 20 hydrogen and 10 oxygen out of 10 water. So you would be looking at about 26 chemical plants just to keep up with a single cryogenic plant producing liquid hydrogen. This can be improved with speed modules but it's still not practical.

The real answer to this problem is to create a new building with a much higher power rating (probably at least 10x). However creating graphics for buildings with multiple fluid inputs and outputs is a nightmare and takes a lot of work, because of Factorio's weird perspective. It took Wube years to get the chemical plant into a high resolution state they were satisfied with. 

So it is on my list of things to do but realistically it's possible that it will never reach the top of the list.
