### ISSUE TITLE
Steam content lost on toggling aetheric lamps

### ISSUE THREAD

**Issue by InappropriatePenguin** [Deadlock989/IndustrialRevolution#167]
**Describe the bug**
When aetheric lamps are toggled, the steam contents of their fluidbox are not copied over to the entity variant they're being replaced by, resulting in a momentary flicker and loss of precious steam. I estimate that I have already lost 12 coal to this issue and I'm worried I may never financially recover.

Ideally, the contents of the fluidbox ought to be copied over allowing the toggling action to appear more seamless.

A related (very minor) enhancement proposal—when toggling an aetheric lamp to the `-end` variant, choose which one of the two sides should be the connected end based on the neighboring entities.

**Factorio version, IR version**
Factorio 1.1.74
Industrial Revolution 3 3.0.8

**Other mods installed**
None.

**Comment by Deadlock989** [comment]
I will take a look at this but I feel like it has come up before and there is some weirdness around the fact that the variant is fast-replacing the old one - I think it is possible that fluid is only lost if there is nowhere else it can flow to, and if there is any space in the fluid system then it flows out and then back in again, but that might be a false memory. At any rate the entity toggle hack already copies a bunch of properties around so it shouldn't be hard to look at fluid contents as well.

**Comment by Deadlock989** [comment]
Yeah, I remembered right. If you have an isolated lamp and toggle it, the fluid is destroyed. But if you have a filled lamp next to an empty pipe, the fluid is preserved because it flows into the empty part of the fluid system and then straight back in again.

![image](https://user-images.githubusercontent.com/3128845/211927160-2fbe6ac6-d567-4045-840b-a835840fd010.png)

I'm not sure how to approach the case where there isn't space in the fluid system, I guess it depends when exactly the fluid levels are recalculated. If it happens as part of the fast replace create_entity call it may not be solvable. I'll look at this again later.

**Comment by Deadlock989** [comment]
There was a reason why it all worked out much better using fast-replace but that reason has also been lost in the mists of time.

I did some testing and fortunately it seems that fluid flowing back in does not happen until the next tick. So the fix was straightforward: record the contents of the entity's fluidboxes, clear the entity of fluids, fast-replace, re-insert the recorded fluids.

Fixing this also partially addresses the same issue in metal casts because they use the same toggle mechanism (and are the only other toggleable entity with fluid capacity). However in that case the situation is more complicated because the fluidboxes are for crafting and not part of the entity's energy source, so the recipe's fluid requirement is taken in one lump every time a new recipe starts and not a tiny amount every tick the way it goes with energy sources. This means that if a recipe is in progress, the molten metal fluid has already been taken out of the fluidbox but the recipe product has not been yet been finished, so toggling the entity still involves a loss because the recipe progress is lost and there is no way of knowing what fluid or how much is in "limbo" with the current API. However, putting the fix above in means that we are now talking about the loss of 10 fluid rather than the full fluidbox capacity of 1k fluid. I feel like this could probably be fixed after extended tinkering but the benefit - saving the occasional blob of molten metal worth a single plate or gear -  just doesn't feel worth the time involved given risks of fluid duping so I'm going to leave it there.

**Comment by Deadlock989** [comment]
> A related (very minor) enhancement proposal—when toggling an aetheric lamp to the `-end` variant, choose which one of the two sides should be the connected end based on the neighboring entities.

This has also been added for the next version.

**Comment by InappropriatePenguin** [comment]
Wonderful—thank you! I appreciate the thoughtful explanations you include in your responses.
