### ISSUE TITLE
Air compressor / purifier module effects

### ISSUE THREAD

**Issue by MaxelDel** [Deadlock989/IndustrialRevolution#182]
"steel-cryo-tower"
"steel-cryo-tower" dosen't accept Pollution Modules.
I have looked into your source code and confirmed that only consumption and speed effects are allowed
I'm running Efficiency_Module_Rebalance_1.0.0 which buffes Efficiency Modules and gives them Pollution reduction.

Cubic Press
If I'm allowed to decrease the Power requirement to cool Gasses shouldn't you also be able to decrease the Power requirement for the Cubic Press? 1 Module Slot like the steel-cryo-tower?

Air compressor vs Air purifier
Air compressor with speed module 1 is more effective than a normal Air purifier.
Maybe add a module Slot to the Air purifier.

To little Sour Gas production
My science stopped because I couldn't produce more Sulfuric Acid.
Maybe increase the rate of the Sour Gas fissure production.

**Comment by Deadlock989** [comment]
- IR3 doesn't provide "pollution modules" and cryogenic towers don't pollute anyway. For machines which do pollute, vanilla efficiency modules already reduce their pollution because emissions are directly proportional to energy usage.
- I'm happy with cubic press balance the way it is.
- I'm not happy with air compressors being boosted by modules/beacons, this wasn't really intended. I will look at this later.
- I'm happy with sour gas the way it is.

**Comment by Deadlock989** [comment]
For the next version, air compressors will no longer accept module effects and have had their slot removed, because the efficiency effect (present in both efficiency and speed modules) works in reverse due to their negative emissions multiplier. A similar set of issues occurred with forestries in IR1, but I had forgotten. Plain efficiency modules (energy usage < 100%) actually reduce their cleaning effect, making them worse at their job instead of better; speed modules (energy usage > 100%) make them disproportionately more effective (the assumption is that with positive emissions they would be disproportionately more polluting). Given the [lack of fine-grained control](https://forums.factorio.com/viewtopic.php?f=28&t=72130) over module compatibility in the current API the only way to balance this is to remove module effects from them completely.
