### ISSUE TITLE
Electric furnace and Medium Steel Pylon overlapping

### ISSUE THREAD

**Issue by TonyDecvA180XN** [Deadlock989/IndustrialRevolution#19]
Issue: Electric furnace and Medium Steel Pylon overlapping. Looks like its cap being hidden.

To Reproduce: build a medium steel pylon right in front of an electric furnace in the middle tile or left tile.
![image](https://user-images.githubusercontent.com/24457508/108501421-54fcaf00-72c2-11eb-8493-02454f1c488c.png)

P. S. Amazing mod by the way)

**Comment by Deadlock989** [comment]
Unfortunately I think this may be a no-win scenario - they were already tweaked a few times so they did not slide underneath things behind them (e.g. inserter arms). But I will take another look.

**Comment by Deadlock989** [comment]
This was indeed a bit of an issue. I can stop the behaviour with the tall power poles but only at a cost of having inserter arms appear over the body of the furnace as well. On balance this latter only looks weird (like the inserter is being permanently roasted by the active furnace) rather than broken (decapitated power poles) so I have gone for the latter.

This is what you get for colouring outside the lines.
