### ISSUE TITLE
Icon for rail block colors in settings menu looks bad

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#192]
**Describe the bug**
In the mod settings menu, the rail block color setting icons look badly rendered, maybe due to my resolution. I can specify if needed. The top left example is slightly smaller, too right is squished vertically/extended horizontally, bottom left is squished horizontally/extended vertically, and bottom right is bigger. The ones above it for machine light colors, laser colors etc look nice. Maybe an internal rounding error?
**Factorio version, IR version**
Factorio 1.1.76, IR 3.0.8 (EDIT: I meant 3.0.11! So sorry for any confusion!)
**Other mods installed**
None of consequence

**Comment by Deadlock989** [comment]
I can see that there is a minor issue at GUI scale 100% (I use 200%) but without giving me details and a way to reproduce what you're seeing, and/or a screenshot of what you're seeing, I can only guess.

**Comment by Cadams111** [comment]
I’ll post a screenshot next time I get a chance, thanks

**Comment by mussii** [comment]
![ir3-1](https://user-images.githubusercontent.com/27778442/218341236-adecfc69-3599-46de-9249-ee95a1944a6f.png)

I see the same thing. I've attached a screenshoot.

Factorio 1.1.76 IR 3.0.12 ( but I've been seeing this issue in all versions )

**Comment by Cadams111** [comment]
Yes, it’s that exactly. Thanks

**Comment by Deadlock989** [comment]
This is being caused by something which probably qualifies as a bug in the base game. When item/recipe/technology items have multiple tinted layers and are used in rich text, the scale and shift of each layer are correctly adjusted with GUI scale. This icon however is defined as a standalone sprite and it seems that rich text references to such sprites are not scaled/shifted correctly at arbitrary GUI scales. All the other icons used in these settings dropdowns are either single layer sprites or references to an item, so they are not affected. A workaround would be to make a dummy item with an icon definition and use that in the rich text instead.
