### ISSUE TITLE
Compatibility with Beacon Rebalance mod

### ISSUE THREAD

**Issue by ray1claw** [Deadlock989/IndustrialRevolution#194]
**Describe the bug**
[Beacon Rebalance mod](https://mods.factorio.com/mod/wret-beacon-rebalance-mod) introduces 3 tiers of beacons with the SE style "beacon overload" mechanic. I'm noticing that with IR3 they are currently placed linearly on the tech tree with no progression in between. I'm also not sure if this was intended or a bug. As such, all three tiers can be unlocked together, which I believe is unlike when the mod is installed with vanilla or K2 eg. (I may be wrong about this one)

Also, I already reached out to [wretlaw120](https://mods.factorio.com/user/wretlaw120) for a fix but they mentioned that you performed the IR3 compatibility and pointed me to here instead.

Current tech requirements:
Effect transmission (Beacon Mk1): RGBPY x 1300 (Prerequisite: Special project Force Fields & Modules 3)
Effect transmission 2 (Beacon Mk2): RGBPY x 1400 (Prerequisite: Effect transmission)
Effect transmission 3 (Beacon Mk3): RGBPY x 1500 (Prerequisite: Effect transmission 2)
_Mods affecting these techs: Beacon Rebalance > IR3_

**Factorio version, IR version**
Factorio 1.1.76 (build 60350, mac-arm64), IR3 3.0.12

**Other mods installed**
(Highlighting relevant mods)
AAI Containers & Warehouses
AAI Loaders
Armoured Biters
_Beacon Rebalance_
_Better AAI Loaders for IR3_
Big Monsters
_Industrial Revolution 3_
_Industrial Revolution 3: Special Projects(ALPHA)_
_IR3: Early logistics system_
Larger Lamps

**Comment by ray1claw** [comment]
Yes, I see the same progression (mentioned in my last post). But compared with Beacon Rebalance when added to vanilla or K2, I'm noticing mk1 is unlocked at purple science but mk2 comes later with purple and yellow and mk3 is unlocked at white science. Mk2 and mk3 also have some prerequisite techs different from t1. With K2 it's obviously different tech cards but the theme is consistent. This is what I meant by tech progression. I've attached some screenshots for you to look over.

With IR3+IR3SP all three techs are lumped together with mk2 and mk3 having no other prerequisites and just needing more science to unlock, so if I just wait and let the save run overnight, I can get access to the fastest tier without bothering with any real effort. This led me to believe that there may be no integration between the two mods.

![image](https://user-images.githubusercontent.com/149414/220175026-dffed52b-ea78-4b12-ae61-abc297b2c56f.png)
![image](https://user-images.githubusercontent.com/149414/220175072-4856e27e-b6fe-45ee-aeea-ac390a040871.png)

**Comment by Deadlock989** [comment]
Beacons in IR3 (without Beacon Rebalance) require yellow science because the techs they are dependent on (force fields and modules) are yellow science. This means the only remaining "progression" in your terms is cosmic ("white") science. Otherwise IR3 enforces very strict prerequisite rules: if a recipe ingredient or science pack is required by a tech, then it must be dependent on the techs which provide those ingredients and packs. So if (for example) I added cosmic science to ET3 then it would also have to depend on cosmic science tech. It's not literally the case that they have no other prerequisites - ET1 can be researched without accumulators but ET2 depends on them - although accumulators are admittedly about 7 levels earlier in the tree.

I don't have any problem with the scheme the way it is now - if I were going to start a new game now with Beacon Rebalance installed I would probably turn the higher tiers of beacon off because I consider them overpowered. But if you can give me concrete details about what you think the prerequisites should be, I can consider them. So far I have nothing to go on except possibly adding cosmic science to ET3.

**Comment by ray1claw** [comment]
Ah thanks for clarifying. At the very least it tells me that this was intended. 

I do agree ET2 and ET3 do get overpowered, which is why the concern. I can't give you concrete details on the prerequisites without finishing IR3 first, but if you think ET2 and ET3 shouldn't exist, maybe these can be disabled by default for new games? If not, adding cosmic science to ET3 can also be a step in the right direction.

**Comment by Deadlock989** [comment]
The only reason I added some level of support for Beacon Rebalance was because I like the "overload shutdown" mechanic and didn't want to re-invent the wheel. I don't want to start disabling other mods' options by default unless there's a really good reason to do it (e.g. Dectorio's overpowered waterfill making IR3's waterfill explosives obsolete) - those choices should be for the player to make wherever possible.

I just looked at adding cosmic science to ET3. It would become the only cosmic science tech that unlocks a new building - every other cosmic science tech is an "infinite upgrade" that increases bonuses, none of them currently unlock recipes. This just makes it feel like an arbitrary "gate" - there's nothing in the ingredients of Beacon Mk3 machines which suggests you need to have visited space. 

4200 yellow science operations to get the top tier of BR's beacons is not a trivial undertaking, and it doesn't bother me that other people might decide to queue all three tiers of tech and then leave their machine running for a day as a "solution" to the obstacle, so I've decided to leave this alone for now.
