### ISSUE TITLE
Inconsistent cost for iron underground pipe.

### ISSUE THREAD

**Issue by Ybaedbaenn** [Deadlock989/IndustrialRevolution#196]
**Describe the bug**
The cost of underground belts and pipes in the mod is proportional to their length.
(yellow underground costs 5 belts and has a max length of 5, red underground - 7, blue underground - 9, copper water pipe/copper steam pipe/iron air pipe - have cost of 10 components and length of 10)
The iron underground pipe has a maximum length of 15, but costs only 10 pipe segments, which seems inconsistent.
Instead the cost of it should be 15 (or the length should be 10).

![image](https://user-images.githubusercontent.com/84321760/219984869-4a3dc223-59d7-4b7c-99d8-2804175d48ba.png)

**Factorio version, IR version**
Factorio 1.1.76
IR3 3.0.12

**Other mods installed**
AAI Containers
AAI Loaders
Concrete Tints
Black Rubber Belts
Helmod
Textplates
Vechicle Snap
Wret Beacon Rebalance Mod

**Comment by Cadams111** [comment]
Nooo don’t nerf my free long distance pipes!
Seriously though, I agree it doesn’t make much sense. 15 iron pipes and maybe rivets could work

**Comment by Deadlock989** [comment]
I don't want to change this because it will retroactively affect people's saved games (e.g. mall set-ups) and that impact is not worth fixing a minor inconsistency. Underground pipes are already very expensive (25 ingots) given that they are used to "duck under" very short distances as often as not. I considered adding a "short underground pipe" variant with only a 5 tile span that was correspondingly cheaper but ran out of time to make a distinctive sprite for them. 

In a perfect world undergrounds would use up a number of pipe items that match whatever number of tiles they span - I am not going to look into that until Factorio 1.2 as that is when we get "linked pipes" anyhow.
