### ISSUE TITLE
Clockwork construction bot speed

### ISSUE THREAD

**Issue by mussii** [Deadlock989/IndustrialRevolution#201]
The description of the first technology "Clockwork construction" states: _"A primitive construction robot. Does not benefit from movement speed research."_

But when I hover my mouse over the bot icon in the techs  "Worker robot speed X" ( for any X) you can see all types of bots (worker, logistic and clockwork) appear in the tooltip. See screenshot attached.

![bug](https://user-images.githubusercontent.com/27778442/221381042-6092ecd1-985a-4217-8c0e-250e34619ac8.png)

It is just a typo of the tooltip or the techs are actually getting applied ? 

If this is not a bug and I misunderstood the first description what does it actually mean ?

**Factorio version 1.1.76, IR version 3.0.14**

**Comment by Deadlock989** [comment]
Re-opening as I noticed a solution to this - flagging the clockwork bot entity as hidden stops it appearing in any bonus GUIs. Doing this has other effects which wouldn't necessarily work out nicely for other entity types, but since worker bots are not upgradeable or fast-replaceable there are no apparent side effects here.

Implemented for 3.0.19.
