### ISSUE TITLE
Feedback: Unupgraded construction bots vs clockwork bots

### ISSUE THREAD

**Issue by Wiwiweb** [Deadlock989/IndustrialRevolution#205]
IR 3.0.14

Not a bug, just a bit of feedback on a small part that caused me a bit of friction, I hope that's ok.

Before the big iron/steel/electricity stage rebuild, I figured I should rush construction bots to have an easier time with the work.

I was disappointed to find out after being done that unupgraded construction bots are strictly worse than clockwork bots: Same cargo capacity, same speed, twice the energy usage.

The very first bot speed upgrade is at a different science pack level, so getting construction bots won't actually give me any advantage for a bit.

I would suggest one of these:
* Make construction bots base speed slightly higher (bake in 1 upgrade level).
* Or make the first bot speed upgrade only require red and green science.
* Or make construction bots tech require blue science so it is not available until it is useful.

**Comment by Deadlock989** [comment]
For context, clockwork bot speed was increased slightly during IR3 beta because they were frustratingly slow prior to that, so this discrepancy only exists because clockwork was recently buffed. 

The reason copper and bronze level equipment has a weirdly low power requirement because there is no non-electric power source available to equipment grids - so in that low level gear electricity kWh are standing in for the same magic that drives burner machines (e.g. burner inserters). Obviously I would prefer to have real steam-driven bots and an equipment grid boiler that feeds them steam, or rotational torque, or literally anything else, but there's no other power option available in the equipment grid API. 

Construction bots do eat more power but by reaching iron and electricity you have also previously unlocked better armour with bigger equipment grids and better burner generators with double the output, so you are no worse off than you were before, and you now have robots that are automatically upgraded by research. There's no rule which says that new tech unlocks have to result in instant improvements - sometimes several tech "steps" are needed.

All that said, I get what you are saying. The middle option of the three suggestions made is probably the most workable. I don't want to buff default bot speed because I feel like I would then also have to buff logistics bots as well; I don't want to shift personal construction bots to steel tier science either because there is no steel in them.

**Comment by Deadlock989** [comment]
I looked at implementing this and decided I don't want to move Worker Robot Speed 1 research either - if it were unlocked before Robotowers, it would mean giving an effective default buff to logistics robot speed as well (worker robot speed tech effects can't be made to apply to specific bot prototypes or even types, see #201).
