### ISSUE TITLE
Polluted water does not show up in the production statistics

### ISSUE THREAD

**Issue by matthew-sharp** [Deadlock989/IndustrialRevolution#206]
I have checked both the fluids and items tab in the production statistics, but polluted water does not exist in either of them near as I can tell. Also near as I can tell, all other fluids (including CO2) are properly displayed. I'm definitely producing some using ore washing, and definitely consuming it in the polluter water cleaner (I don't have any heat exchangers).

Factorio 1.1.76, IR 3.0.14

I still get this if IR3 (and dependencies) is the only mod loaded. Previously on this save the mods I can think of that would be remotely relevant:
* Realistic Fusion Power
* Fluid Wagon Color Mask

**Comment by Deadlock989** [comment]
Polluted water outputs from washing need to be marked with the [catalyst_amount](https://wiki.factorio.com/Types/FluidProductPrototype#catalyst_amount) property because that is the only way of preventing that part of the recipe product being multiplied by productivity module effects while still having the mineral output affected. Catalyst products are not shown in statistics. There is nothing that can be done about this with the current state of the game (short of banning the washing recipes from being affected by productivity at all). Personally the way this mechanic works doesn't bother me but other people have felt it should be addressed ([for example](https://forums.factorio.com/viewtopic.php?f=28&t=104949)).
