### ISSUE TITLE
Steam inserters do not show inserter arrows when option to show inserter arrows in alt mode is enabled

### ISSUE THREAD

**Issue by KSPAtlas** [Deadlock989/IndustrialRevolution#210]
I am running IR3, and as I am transitioning into the electric phase, i noticed that steam/long steam inserters do not show inserter arrows in alt mode, while electric ones do. Is this too niche to fix?

**Comment by Deadlock989** [comment]
I had never noticed this because I have inserter alt-mode arrows turned off in Settings > Interface, it's information overload for my tastes.

Looking at the code I can see that inserter arrows have deliberately had alt-mode info turned off and it has been that way since they were introduced in IR2. It was most likely done because of the steam-filtered energy source fluidbox connectors on the inserter. 1x1 entities with more than one pipe connection (steam inserters have 2) end up with multiple alt-mode fluidbox filter icons drawn dead centre, one for each fluid connection. The fuzzy black outline Factorio puts on them is doubled up and looks extra thick and black. For icons with soft translucent edges (like steam) the same thing happens, the translucent edges "stack" and look bad. This is avoided for some other 1x1 entities (especially where there are two different filters that really need the alt-mode filter icons to remain distinct, e.g. ambient heat exchangers) by moving the fluidbox location further out from the entity, but it doesn't work well with all entity types. You can check this out for yourself by commenting out `code/entities/entities-inserters.lua` line 88. It looks like this:

![image](https://user-images.githubusercontent.com/3128845/225142780-86c4172c-fb40-4167-a954-b518493643d7.png)

Unfortunately the API provides no way that I know of to disable fluidbox filter icons but keep other alt-mode info, it's all or nothing.

You still get the direction arrow if you mouseover the steam inserter, which doesn't count as alt-mode.
