### ISSUE TITLE
Inconsistent uranium fuell cell/used-up cell stack size.

### ISSUE THREAD

**Issue by Ybaedbaenn** [Deadlock989/IndustrialRevolution#213]
**Describe the bug**
Uranium fuel cells stack to 10 in IR3, while used-up uranium fuel cells stack to 50 which is inconsistent. (In vanilla Factorio both items stack to 50)
Instead both items should stack to 10 (or to 50).
![image](https://user-images.githubusercontent.com/84321760/226118808-0755cd51-5c07-445e-aa98-a75d6a0a4873.png)

**Factorio version, IR version**
Please confirm your Factorio version number and the Industrial Revolution version number.
Factorio -1.1.77
IR3 - 3.0.15

**Other mods installed**
Other mods installed
AAI Containers
AAI Loaders
Concrete Tints
Black Rubber Belts
Helmod
Textplates
Vechicle Snap
Wret Beacon Rebalance Mod

**Comment by Deadlock989** [comment]
What problems does this cause?

**Comment by Ybaedbaenn** [comment]
It does not cause any problems (at least for me), but does bot make logical sense.
I already solved this for my save by adding ```data.raw.item["used-up-uranium-fuel-cell"].stack_size = 10``` in items-vanilla.lua, so if it may cause errors for other users it may be better to leave it without changing.

**Comment by Deadlock989** [comment]
I'm happy to tolerate minor logical inconsistencies - this is a game where a human can put 1000 oil refineries into their pocket after all, realism was never Factorio's focus. I guess ideally the stack sizes would match but I'm reluctant to make changes which can affect games in progress when there's no actual problem to solve. Increasing the active cells back to 50 would probably hurt saved games less than cutting spent cells down - but the fuel cells stack size has been that way for a few years now (since IR1 I think) and I no longer recall the reason why it was lowered in the first place - I think it was mostly likely the massive energy value they carry combined with the fact that they are additionally used as equipment grid fuel. 

I'll make a decision about this some other time.
