### ISSUE TITLE
Issue of fuel slots for non-vanilla non-IR3 vehicles

### ISSUE THREAD

**Issue by Chlebek11** [Deadlock989/IndustrialRevolution#216]
Vehicles provided by other mods do not have slots for spent fuel, and only accept wood products, coal, coke and charcoal. Is it possible for IR3 to check for such vehicles and add required slots automatically OR come with snippet of code prepared to be pasted into such mods?

Factorio 1.1.76 IR3 3.0.15

Cargo Ships, Aircraft.

**Comment by Deadlock989** [comment]
This issue seemed to disappear for 24 hours, I have no idea why - I received an e-mail notification yesterday about it and then when I visited Github it had gone. It reappeared today with no further notification.

In theory it would be possible - you could loop through every vehicle the mod can find and increase the "burnt inventory" size to match the fuel inventory size, and also add all of IR3's custom fuel categories - but I am reluctant to add code which unconditionally modifies vehicles from third party mods for a few reasons, the main one being that there is no way for a Lua script to determine whether it would make sense for (e.g.) a helicopter to run on batteries, rocket fuel or a barrel full of petrol. The best way to handle it is to tailor third party mod support for those specific third party mods, and there is a very limited number of third party mods that I am personally prepared to commit to supporting. Another issue is load order - this would have to be done as late as possible in the prototype loading sequence or it is very possible that unknown third party mods will be missed out due to loading order, whereas if you are deliberately trying to support a specific mod then you can influence loading order to make sure that it will work.

If you look at lines 50-63 of `code/entities/entities-vehicles.lua` you can see how the vanilla vehicles are handled. In those cases, the number of burnt inventory slots is increased to match the fuel inventory (the burnt inventory must be at least as big as the fuel inventory assuming equal stack sizes, because otherwise the vehicle will never be able to consume all of its fuel) and also adds the IR3 fuel categories. The vanilla category which includes wood, coal, solid fuel and a couple of IR3 fuels such as charcoal is `chemical` - most mod vehicles will already support this. The IR3 categories are `battery` (rechargeable batteries), `canister` (IR3 pressurised fuel, analogous to vanilla rocket fuel) and `barrel` (any barrel that contains fluid with a fuel value).

**Comment by Chlebek11** [comment]
The issue of issue disappearance probably has to do with Github's internal workings, for they have suspended this freshly new account for zero reason whatsoever.

And thanks for the detailed answer, it'll surely help with creating compatibility mods for personal use.
