### ISSUE TITLE
Excess of secondary minerals when using water washing.

### ISSUE THREAD

**Issue by Ybaedbaenn** [Deadlock989/IndustrialRevolution#219]
**Describe the bug**
Even in the basic water ore washing processes, the amount of pure chromium, nickel, and platinum minerals produced is excessive in comparison to their required consumption and the amount of their respective primary outputs.

In my save where I have just automated rockets (94 hours), I use water washing for all of my ore (for extra primary resources efficiency), arc smelting for primary minerals, and regular smelting for the secondary ones (except lead). With that, I have hundreds of thousands of secondary minerals ingots (except for lead) stored in warehouses so far.
![image](https://user-images.githubusercontent.com/84321760/227337484-9a032f47-420c-4af3-af8d-e457fb09fbe1.png)
![image](https://user-images.githubusercontent.com/84321760/227338042-092c31cf-60f5-4cfa-afc1-b6740ec88c2a.png)
![image](https://user-images.githubusercontent.com/84321760/227338509-987a89a1-a496-4b75-9060-902112999edd.png)

I know from the Factorio Discord server that other IR3 players have experienced the same issue as well.

The overproduction of 3 out of the 4 secondary minerals makes the secondary acid washing (which loses the possible challenge of balancing between the two washing options) and arc smelting recipes for the minerals mostly pointless.
There are also currently no interesting ways in the mod to deal with the by-products (they can be disposed of with the bottomless pit that is said to be optional in mod's settings, or regular crushed ore smelting must be used to not overproduce them at the cost of lower ore efficiency).

As shown in this tool:
https://factoriolab.github.io/list?z=eJwrcA.VMjOIdw8Dk4lgMhxMRoDJSDAZBSTVklLU0gzj0-OD4uMj4hPj3dWKtQy1tLRc1MrMAaHbEx8_&v=7
Producing equal amounts of every analysis pack in a late-game, fully moduled build leads to a small overproduction of pure chromium minerals, a medium overproduction of platinum, and a huge (nearly 200% of the required) overproduction of nickel. While lead is the only mineral that is used in a high enough quantity to require arc smelting and acid washing.

Instead, the secondary outputs for the recipes should be reduced or the primary outputs increased.
Other possible ways to deal with the problem include:
- additional secondary minerals required for some recipes (that are used in science),
- analysis pack ingredients requiring less primary resources
- adding new, alternative recipes, that will allow the player to wash the ores in a different way (with lower by-product yield),
- adding new, alternative recipes to produce science components with more secondary minerals (possibly also requiring less of primary ones for extra efficiency).

I know that these (or some other) changes may be save-breaking for the players of the mod, but I wanted to make sure that you were aware of the issue so that it can be resolved in a next major version of the mod (e.g., 3.1 if you are planning on making it).

**Also, thanks for the great mod!**

**Factorio version, IR version**
Factorio - 1.1.78
IndustrialRevolution3 - 3.0.15

**Other mods installed**
aai-containers
aai-loaders
Concrete-Tints
cybersyn
DeadlockBlackRubberBelts
flib
helmod
Orphan Finder
textplates
VehicleSnap
wret-beacon-rebalance-mod

**Comment by Deadlock989** [comment]
I am aware of these issues and sought feedback on them during the limited beta of the mod, but didn't really get much help. Earlier versions had the opposite problem: there was an extremely frustrating hump just before "late game" kicked in where it was very, very difficult to produce enough nickel to bootstrap certain technologies. This lead to the removal of sapphires, which were a big consumer of nickel. Additional tweaks on top of that then got things to where they are now, where the balance is probably tilted too far the other way. Essentially there is an argument that I can't easily refute, that this is a fundamental design flaw in the IR series, i.e. fixed ratios of metal by-products are always going to result in either too much or not enough unless end-game product recipes are balanced with tedious precision.

That said, I think there is one thing being overlooked by many people who want to scale the mod past launching one rocket: there is nothing forcing you to wash all of your ore. If you have an excess of nickel, don't make nickel. "Smart" furnace lines can easily be arranged to have the crushed copper ore bypassing the washing subfactory completely where necessary, going straight to the furnaces, and this is how my SPM-focused games ended up post-beta. 

With regard to arc smelting, it's there for interest/variety more than anything else - the in-game docs do point out that it's optional and it's more about the fluid transport possibilities than being a direct upgrade to regular mineral smelting.

If there are going to be ingredient changes for common late-game consumables such as rocket launches or high tier science packs, I need actual suggestions for actual recipes, ideally backed up with in-game stats or spreadsheet simulations of such.

Otherwise the only other "solution" is to add a by-product free version of water washing, but given that washing machines can't auto-select recipes due to game engine limitations with fluid and/or multiple-input recipes in furnace-type entities, this would result in people having to double up washing factories - it would be simpler if they just smelted crushed ore as intended.

**Comment by Wiwiweb** [comment]
> Essentially there is an argument that I can't easily refute, that this is a fundamental design flaw in the IR series, i.e. fixed ratios of metal by-products are always going to result in either too much or not enough unless end-game product recipes are balanced with tedious precision.

It seems like if you had 2 washing recipes, one being "not enough byproduct" and the other being "too much byproduct", then you'd have to use a mix of both in order to fill your factory's needs perfectly, which sounds like an interesting challenge. Either with perfect ratios if you're just doing SPM, or with prioritization splitters/circuitry if your needs are variable.

At the moment it sounds like the issue is the water washing recipe is "too much byproduct" and the acid washing recipe is "way too much byproduct", so this isn't possible. 

> Otherwise the only other "solution" is to add a by-productless version of water washing

What about only reducing the byproduct ore output of water washing recipes to make it "not enough byproduct"?

**Comment by Ybaedbaenn** [comment]
> If there are going to be ingredient changes for common late-game consumables such as rocket launches or high tier science packs, I need actual suggestions for actual recipes, ideally backed up with in-game stats or spreadsheet simulations of such, that compare the proposal to the status quo. I have attempted such things myself but I have finite time and motivation available.

I might be able to suggest some recipes in a few days, as I already made some changes to the mod for my save, like adding nickel (ingots) to hull sections, but first I will try to think of a few more and check the possible impact in-game and/or with (modified) https://factoriolab.github.io.

**Comment by Deadlock989** [comment]
> The main issue with adding the resources into recipes seems to be the small amount of available intermediates made from the secondary metals. Nickel, especially, only has pellets as an intermediate product (excluding the plating solution), which being used outside of chemical processes wouldn't really make logical sense. Having nickel plates or gears (while may cause unnecessary clutter) would make it easier to "spend" nickel in some recipes.

This is definitely a contributing factor to the lack of uses for nickel but returning to having basic nickel components would be going back in a circle. IR2 had stainless steel in between steel and chrome; it was a moderate consumer of nickel and a minor consumer of chromium but was widely regarded as one tier too many. IR3 beta initially replaced stainless with nickel plating (steel + nickel plating solution) - it was only used for military applications by itself such as ammo, turrets and military vehicles, but nickel-plated components were also a "base plating layer" for chroming (i.e. chrome plating was steel component + nickel plating solution > nickel-plated component + chrome plating solution > chrome-plated component). But very few people, myself included, really liked having so many basic components in so many different flavours - that feedback was loud and clear, if rarely constructively expressed, ever since IR1. "Double dipping" for plating was also an unreasonable consumer of acid and ethanol initially. So, given that I was running out of free time and wanted the mod done, I consolidated the electroplating into one process.

So bringing back nickel plates and gears would just be winding back the clock in this regard. I'm much happier with where the basics / intermediates are now and don't really want to go back to the way it was. The real issue is that (a) people think they need to completely replace crushing with washing when actually they don't, and/or (b) that the available uses of some by-product metals, particularly nickel, have been reduced to the point where the 25% byproduct chance in water washing is always excessive and acid washing is hardly ever needed, despite trying to mitigate this by slashing the copper use of e.g. rocket launches. Which brings us to:

> What about only reducing the byproduct ore output of water washing recipes to make it "not enough byproduct"?

Yes, but, reducing it to what exactly, remembering that there is a tech gap between water washing (Ore Washing 1 tech) and acid washing (Ore Washing 2 tech) that you need to be able to bridge?

**Comment by Ybaedbaenn** [comment]
> IR3 beta initially replaced stainless with nickel plating (steel + nickel plating solution),

Adding nickel plates does not have to necessarily add that much; I was thinking of them being made directly from nickel ingots like most other intermediates, as it makes more logical sense to add those than ingots to recipes (and using enough nickel with only pellets and as a small ingredient in the plating solution seems to be impossible).

Other minerals don't have this extent of the problem, because even with no plates or gears:
- platinum is used as a pure mineral for electrum,
- chromium is the main ingredient for electroplating,
- lead (has plates but also) is used as pure mineral in the long range radio.

Clutter can also be avoided by reducing the number of intermediates other metals have. I especially think that there are too many different pellets.

> People think they need to completely replace crushing with washing when actually they don't,

While this is true, they have a reason to think this way: washing ores is more efficient for the primary metals. And while the efficiency bonus may not seem this big (1.5 -> 2), it gets big (1.5 -> 3) when arc furnaces are researched (and arc furnaces only work with pure minerals and not crushed ores).

> There is a tech gap between water washing (Ore washing 1 tech) and acid washing (Ore washing 2 tech) that you need to be able to bridge.

The tech gap seems not to be too important to me:
![image](https://user-images.githubusercontent.com/84321760/227732207-d25d2ee0-a591-4d11-99ec-2908f84fff3c.png)
As both techs are steel analysis pack tier. So for a player who automated the packs, it's only a matter of waiting a while to get both water and acid washing.

(Btw, it seems weird to me that Ore washing 1 has batteries as a prerequisite, but the washing plant does not require them to be built; it only requires acid, and only for Ore washing 2. Are the prerequisites for both technologies intended this way?)

---

I have made and tested (out of game) some changes to some recipes:
- reduced secondary mineral outputs from 0.25 to 0.20 for all water washing recipes,
- changed lead pellets to nickel pellets for ethanol production (from gas); now lead pellets have no uses and can be removed,
- added one chromium ingot to the copper foam recipe,
- added one nickel ingot to the steel foam recipe,
- reduced the number of pellets made from one ingot from 4 to 3 for all relevant metals,
- added two nickel ingots to the hull section recipe,

Result (calculated in a local Factorio Lab instance with modified data):
https://skafrex-cdn.ml/images/FactorioLab00.png

Factorio Lab data:
https://skafrex-cdn.ml/text/data.json

The result is that for late-game, fully moduled bases, now both water and acid washing of every ore are required; however, the margin of acid washing being needed is still very small for some minerals.

Please tell me what you think of those changes and if the altered recipes make logical sense. Feel free to ask for more information, details, or propositions.

**Comment by Deadlock989** [comment]
Thank you for taking the time to do this and also for being specific. 

Some elements of this might turn out to be useful but there are other suggestions here which I don't ever see myself making (e.g. nickel components, adding secondary metals to foams). At this point I don't know how I feel about acid washing becoming compulsory for all four main ores and I'm pretty much ambivalent about rebalancing the mod around infinite science (I generally lose interest in a map around the time rocket launches become realistic). I would want to do a playthrough of any changes on this kind of scale to see how the post-washing mid-game plays out, but that isn't going to happen in the near future due to having other commitments and being a little burned out with Factorio in general. When/if I do start a future refresh of the mod (e.g. IR 3.1) then I'll return to this thread and experiment.

> Are the prerequisites for both technologies intended this way?

Yes, probably. While much of the tree is automatically generated from recipes, a number of manual prerequisites were added purely to de-clutter, e.g. to eliminate very long prerequisite links and reduce large horizontal spreads / bottlenecks.
