### ISSUE TITLE
Unannounced lab deletion on opening

### ISSUE THREAD

**Issue by danielbrauer** [Deadlock989/IndustrialRevolution#221]
**Describe the bug**
When opening the manifest, IR raises an event when it revives a lab, but fails to raise an event when it is destroyed. To reproduce:

1. Enable IR3 and DiscoScience mods
2. Start a new game
3. Push 'I' to open the manifest

**Factorio version, IR version**
Factorio 1.1.74
IR 3.0.16
DiscoScience 1.1.3

**Other mods installed**
DiscoScience does not change game content, but it tracks all labs in order to draw animations on them. It expects creation and destruction events to be paired, otherwise it has to perform an expensive call to find all labs.

This ought to be fixable by adding `raise_destroy=true` to `Destroy` calls, or _not_ passing `raise_revive=true` when reviving.

**Comment by Deadlock989** [comment]
I had a look at this. It's true that there is a destroy call for Manifesto labs which doesn't raise an event, and that's easy enough to address. But I'm not clear on why DS is raising such a forceful error-in-a-speech-bubble to players just because it detects a missing lab. Why not just de-register it when it's been detected as no longer valid? 

In IR3 the lab entity doesn't use the vanilla lab animation at all, but it seems that DS is still drawing something on top of it which looks like it's designed to overlay the vanilla animation, so there's a fundamental mismatch there. There are also two other IR3 labs which aren't handled. I think the best solution here is to mark DS as incompatible.

**Comment by danielbrauer** [comment]
I agree: if you're using different lab graphics then making these mods work together is not trivial.

With respect to the noisy error: I do work around the underlying problem, but I figured it would be helpful to let other mod authors know when they haven't paired their create/destroy events properly. 

Thanks for looking into it!
