### ISSUE TITLE
Carbon Dioxide Transportation

### ISSUE THREAD

**Issue by theironrelic** [Deadlock989/IndustrialRevolution#229]
I have been working on creating a gigantic natural sanctuary island using forestries and I've noticed some serious issues with transporting carbon dioxide efficiently. While I can barrel fertilizer, and that seems intended, it seems there is no way to thematically transport carbon dioxide other than loading it into fluid wagons (or I guess, fluid ships since I'm using cargo ships).

Is there a reason you can't liquify carbon dioxide like you can with other gasses (nitrogen, hydrogen, oxygen etc) or put the liquid CO2 in cannisters? Seems like liquefying and cannistering C02 would go along with other types of similar fluid removal, like barrelling polluted water (a similar pollutant) or barreling fertiliser (the companion to C02). 

Maybe an alternative would be to add a recipe to the cryo plant to allow it to just extract C02 on site.

Thanks for the mod, I'm having a lot of fun making a gigantic base and designing forestries everywhere btw!

Also this is technically unrelated, but I made a compatibility patch for the mod cargo ships, and as part of the patch, I wanted to make the Cargo Ships recipes match the difficulty and spirit of Industrial Revolution 3, but I obviously can only interpret what that means. I have the recipes described on the [FAQ](https://mods.factorio.com/mod/IR3CargoShips/faq) of the mod page, if you have any suggestions on the recipes as the original IR3 source, I'd love to hear some suggestions, especially as several people have suggested I make the recipes easier, or have automated ship transport be before steel rather than after it.

**Comment by Deadlock989** [comment]
The reason is simple: I didn't add it. CO<sub>2</sub> was introduced pretty late in the day. Also, currently, adding canisters is harder than adding barrels because there isn't an icon mask set up for canisters the way there is for barrels, so every canister icon currently has to be generated.

In the real world, my chemistry/physics isn't all that great but I'm also aware that liquid CO<sub>2</sub> is a bit tricky. In its "true" liquid form, it only exists in a pretty narrow range of temperatures and only over ~5 atmospheres - it can't exist at all at Earth ambient conditions. There is such a thing as supercritical CO<sub>2</sub> which also needs high pressure and acts like a gas with the density of a fluid. At the moment liquid/SC CO<sub>2</sub> is mainly shipped around in trucks and occasionally tanker ships. There are industrial lobbyists pushing to have transnational and international CO<sub>2</sub> pipelines but folks seem reluctant to take on something which would need so much maintenance and have non-trivial health any safety issues.

None of that necessarily has to apply to a game of Factorio/IR3, admittedly, where we currently have the same pipes transporting water, liquid helium and molten chromium. So I suppose there is no reason why liquid CO<sub>2</sub> couldn't be added, along with cryo recipes and canister filling. It just needs the work and time, and those are currently in short supply. 

I will look at this again if there is ever a 3.1 release.

**Comment by Deadlock989** [comment]
Liquid CO<sub>2</sub> and canisters added in 3.0.19.
