### ISSUE TITLE
Mixed Forestries having weird results.

### ISSUE THREAD

**Issue by theironrelic** [Deadlock989/IndustrialRevolution#233]
When I have a large mixed forest with several rubber trees and non rubber trees. I know the forestries auto default to just rubber forestry if there are even one rubber tree, but it seems the ability to count trees is maxed out within the chunk.

<img width="798" alt="Screen Shot 2023-05-23 at 8 42 01 AM" src="https://github.com/Deadlock989/IndustrialRevolution/assets/43525812/14dd07b0-1cf7-48b3-8323-802e6020d56b">

This chunk is an example, there are clearly lots of rubber trees but the forestry only counts a couple of them before giving up.

Maybe if you could manually switch between rubber and normal wood, the forestries could be better able to finding the right trees in the chunk?

**Comment by Deadlock989** [comment]
This is an error in the tree counting logic - to cap the UPS used by the periodic forestry scan, there is a bailout when the effective maximum count for either of the tree type is found, but this doesn't take into account that there might be more than zero rubber trees and more than the maximum number of regular trees. The kind of situation shown in your picture might sometimes work because it will depend on the order Factorio's entity search returns the trees.

**Comment by Deadlock989** [comment]
Fixed for next version.

When the fix becomes available, any forestries currently affected will take some time to update. You can force it to happen early by removing and replacing the forestry or any tree within the forestry's chunk.

**Comment by mussii** [comment]
I don't know if its related but if you plant Dectorio trees ( not the ones that you can create from the IR3 mod ) the forestries do not recognise them. 

I'll try to reproduce it if you want. @Deadlock989

**Comment by Deadlock989** [comment]
> I don't know if its related but if you plant Dectorio trees ( not the ones that you can create from the IR3 mod ) the forestries do not recognise them.
> 
> I'll try to reproduce it if you want. @Deadlock989

I don't have any trouble with Dectorio trees here. The only thing I can spot is that the tree name has a missing localisation in the crafting menu recipe title but I don't think that's an IR3 issue. All of the Dectorio trees that IR3 sets to costing 12 wood should work, the others are dead or dried trees and those types do not work with forestries by design.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/1c668801-9172-4599-9d3b-775ddee6ed90)

If you can reproduce some issue with Dectorio trees then please create a new issue and give reproduction steps, thanks.

**Comment by mussii** [comment]
I think it did not work because the chunk where I was doing it had too much pollution. 

I went far away from my base and tested it and the forestry recognised the trees instantly. 

Thanks!
