### ISSUE TITLE
Forestry on desert planets

### ISSUE THREAD

**Issue by eus-tach** [Deadlock989/IndustrialRevolution#237]
**Describe the bug**
Hello Deadlock. First of all thank you for the great mod. For me this is THE mod and I do not play Factorio without it. Played for hundreds of hours and never reached the final stages of the game. :) I just love the slow pace of your mod. IR3 version promises to be worthy improvement and making the age of coal and steam longer then in previous version is a way to go, at least for me.
However the forestry changes in IR3 pose some problems for me. I am one of those players, probably there is only handful of us, who plays on desert planets, without any trees/rubber trees. I prefer desert planets and forestry industry makes more sense on such planets. But IR3 forestry does not work on non-trees planet.
I know that you've put a lot of work in this and other improvements in IR3, but would you consider to introduce some changes to forestry to make desert planets a feasible configuration for IR3?
I'll understand if you do not find the time for it, as this probably would require some significant changes to forestry. Regardless, thank you again for the great mod.

**Factorio version, IR version**
latest IR3 version and latest factorio version

**Other mods installed**
Only small QoL mods.

**Comment by Deadlock989** [comment]
Thanks for the compliment.

My options are pretty limited here. It's true that there are possible map configurations which are unplayable, but this is true for vanilla as well (e.g. turning off coal or copper would effectively produce an unplayable map unless you installed some mod to provide another route to them). IR3 is even more dependent on wood and rubber than in earlier versions so turning off wood is effectively going to make the game at least very difficult if not outright impossible. I don't want to change the forestry process itself to cater for this, but there may be other options.

When you say "desert planets without any trees" do you mean that you are turning off all spawning of trees like so:

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/498834a1-f5a9-4521-8f12-a96969fdc40c)

Or do you mean that the moisture, terrain type and water settings you have chosen are preventing the spawning of rubber trees? Please clarify, because if it's the latter, then it should still be possible to kickstart forestry except on the most extreme of settings.

Another change in IR3 compared to IR2 is that the starter kit options are more limited. Previously you could opt for a bonus resource kit in any starting era that included both wood and rubber wood, enabling you to kickstart forestry even on extreme maps or if you have some third party terrain generation mod that interferes with trees. In IR3 the "Starting technology level" option is more limited (on purpose), but I now notice that you need to select at least "Iron" or above in order to get any rubber wood. That feels like an oversight - there is no reason rubber wood can't be made available in all of the post-Stone options. So I can make that change at least, and add some context for this in the map generation settings tooltips for trees and rubber trees.

Another option is some chemical route to rubber, or maybe a plastic-based route to heavy copper cables, but to be honest I'm reluctant to circumvent existing recipe chains just because the game engine makes it possible to start a map without trees, so I don't think this is likely to happen.

**Comment by Deadlock989** [comment]
Pending further info I have made the following changes for the next version:

- Rubber wood was added to the "Copper" and "Bronze" starting tech levels, i.e. it is now handed out for every level except the default "Stone"
- The amount of wood and rubber wood in starter crates was doubled
- If either trees or rubber trees are completely disabled in map generation settings, and the starting tech level is the default "Stone", the option is effectively bumped up to "Copper", i.e. woods are available in the starter crates and a handful of low level automation techs are pre-researched

**Comment by eus-tach** [comment]
Hi Deadlock,

Thank you for the proposed changes. It is a nice tuning. Previously when starting at stone level (always) I needed to add a 100 wood/rubber wood through console. Now I will have them by default.
I play maps as it is shown on your picture: by disabling tree spawning in map options. I understand your reluctance to introduce changes in recipe chains. You shouldn't change anything in that area, I agree. But maybe some simple tuning would be possible: forestry will work/produce at some minimum level, higher than 0 (current situation), when no tree is present within forestry area?
If not, then I will have to turn the trees on in the map settings. Not my desired solution, but I can live with that :)
I dream of some "realistic' tree plantations, that will take a lot of ground and complex water system based on water pipes and other automatic harvesting options. But that is probably way beyond capabilities of current mods API for mods. It would be cool though, an extra challenge on desert planets.
Thank you Deadlock for your efforts, I appreciate it greatly.

**Comment by Deadlock989** [comment]
> ... But maybe some simple tuning would be possible: forestry will work/produce at some minimum level, higher than 0 (current situation), when no tree is present within forestry area? If not, then I will have to turn the trees on in the map settings. Not my desired solution, but I can live with that :) I dream of some "realistic' tree plantations, that will take a lot of ground and complex water system based on water pipes and other automatic harvesting options ...

I feel like there is some miscommunication or misunderstanding here - have you played IR3 yet? The reason for making sure that some wood is available in the starter crates is that then you can craft and plant your own trees to start a forestry off. You need 12 wood to craft one tree bed, which would be enough to start a forestry off all by itself, although this would be very slow, so currently 100 (and in next version 200) wood will be provided to get at least one forestry chunk off to a moderate start. Normally you would gather some wood yourself (and have to locate rubber trees), but if they are disabled in map settings then some wood will now be automatically available for you to craft tree beds with (without having to select easier starting technology levels). 

Forestries do also require water transport in IR3.

**Comment by eus-tach** [comment]
Well, it seems that my dreams came through, then. :)
yes, I played IR3 and crawled slowly to my first bronze forestry, provided it with water but no production has started. It seems I completely misunderstood the process, then. I will jump in to my last save and start playing with trees :)
TY again!

**Comment by Deadlock989** [comment]
Expanded tooltip for the starting tech setting in next version.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/7262eb38-3583-47ef-8e9c-32301b100e99)
