### ISSUE TITLE
Transmats inappropriately retain some properties after being mined + UI entry duplication

### ISSUE THREAD

**Issue by InappropriatePenguin** [Deadlock989/IndustrialRevolution#25]
_Issue:_ If a transmat is mined by the player and is then manually replaced in the same exact spot (ie. without using "undo"), the newly placed transmat will retain the same name in the UI, though _without_ showing that name under that transmat in alt-mode. Furthermore, that entry will be duplicated in the transmat UI if you open it from a second transmat.

<img width="672" alt="Transmat" src="https://user-images.githubusercontent.com/72840021/108988475-f1052c80-76ad-11eb-9c11-be1ef8fcfd3f.png">

_Expected behavior:_ Newly placed transmat should not inherit any properties from the previous transmat that was in the same spot. Transmat should not be duplicated in the UI.

Factorio 1.1.25

Industrial Revolution 2.1.2
Editor Extensions 1.9.8
Factorio Library 0.7.0

On a sidenote—thanks for making such a wonderful mod :)

**Comment by Deadlock989** [comment]
There are two or three related issues here.

1. The script doesn't check for any existing cached transmat data for a tile position when a brand new transmat is manually placed there (the main thing causing the duplication in the transmat GUI).

2a. Transmat name caches aren't removed if the transmat is destroyed or manually mined.

2b. Transmats built from blueprint ghosts get their name from the blueprint tag data, but transmats built from ghosts created by the destruction of a transmat rely on the name cache (see 1) which is why they don't get their alt-mode rendered name.

I have fixed issue 1 for the next version. The other part requires more thought/work. I guess really the name cache should be removed on any kind of removal or destruction and put into the ghost if there is a ghost. And then undo probably has to be handled as well.

**Comment by Deadlock989** [comment]
So I have this working better, but not exactly how train stops work, which is the benchmark - but it's good enough.

If transmats are "killed" by biters or other damage and a ghost is created, the name is put into the resulting ghost and is correctly reassigned (and rendered in alt-mode) when the ghost is revived. However the name will just be deleted if they are manually "picked up" or if a script from some other mod deletes the entity without "killing" it. This means that if the undo key is then used to make a ghost of the manually removed transmat, there is no data now to restore. 

Train stop names survive undo - I assume that's some native property of the train stop entity that just doesn't apply to anything else (transmat names are cached in a lookup table instead). If there is some trick to keeping arbitrary data hanging around for the undo queue that can be accessed via scripts when undo creates a ghost, I don't know what that would be, but I don't think there is.

**Comment by InappropriatePenguin** [comment]
I think that's a very reasonable compromise. Losing transmat properties on undo is a very minor inconvenience if they're otherwise behaving as expected in other settings.

There had been some other quirks I was encountering with transmats, though they were both harder to explain and reproduce. I do strongly suspect that they stemmed from the same issues that you've already addressed here, so hopefully no further work on this will be needed.
