### ISSUE TITLE
Inserters stuck when insert components into assembler

### ISSUE THREAD

**Issue by Proha5** [Deadlock989/IndustrialRevolution#259]
Assembler craft chemical factory. Inserter (capacity 3) insert concrete into asembler and stuck. Because input slot already have 99 concrete. And limit is 100. I have this problem in other recipes. (oil refiney, warehouse e.t.c.)
I was meet this roblem in other modpack. But only if speed of assembler over 50. Here i don't speedup assembler (speed is 2.5).

**Comment by Deadlock989** [comment]
There is a [template](https://github.com/Deadlock989/IndustrialRevolution/issues/new/choose) for reporting issues where I ask you to describe the problem, give reproduction steps, tell me what you expect should happen instead, and list all of the other mods that you have installed. So far nothing you have said gives me any idea what you think the problem is and without the information I need I can't do anything.

**Comment by Deadlock989** [comment]
This is a base game issue which has been reported many times to them, for example [here](https://forums.factorio.com/viewtopic.php?f=23&t=106779&p=586443) and [[here](https://forums.factorio.com/viewtopic.php?f=48&t=77301&p=580341#p580341)](url). There is nothing I can do about it.

You have two choices: either limit the inserter to pick up one item at a time using "Override stack size" in the inserter GUI, or design your constructions lines differently so that multiple inserters can feed one assembler with different products.

**Comment by Proha5** [comment]
Ok. Understand. But other modpack no have this problem. Probably other mods fixed this vanila bug.
