### ISSUE TITLE
Suggestion: Circuit network & Filter wih loaders

### ISSUE THREAD

**Issue by tundy** [Deadlock989/IndustrialRevolution#277]
**Describe the issue**
Hello,
1. Would it be possible to be able to use red/green wires with loaders?
2. And to add a filter version of loaders?

If not for all, maybe only with electrical loaders?
And steam loaders can be as they are now.

**Factorio version, IR version**
[Industrial Revolution 3: Powered Loaders & Ingot Stacking](https://mods.factorio.com/mod/IndustrialRevolution3LoadersStacking) v1.0.1

**Comment by Deadlock989** [comment]
Loaders aren't equipped with circuit control behaviour, this is something that only the Factorio devs can add. It could possibly be "faked" with very heavy scripting and invisible composite entities but this isn't something I'm willing to explore because it would be bug-prone and bad for performance. Instead, 99% of the time, you can simply control the belt that's attached to the loader.

The loaders do already have filters. These are only shown and only work when the loader is in output mode. Yellow loaders (steam or electric) have 1 filter, higher tiers have more.
