### ISSUE TITLE
Supported mod recipes (concrete, decoratives)

### ISSUE THREAD

**Issue by ZombieKM** [Deadlock989/IndustrialRevolution#280]
**Describe the issue**
Every recipe using Concrete was changed to use Concrete Blocks in IR3.1 except for these 2 mods. I wasn't sure if this was intentional or an oversight and wanted to bring attention to it.

**Factorio version, IR version**
Factorio Version: 1.1.87
IR Version: 3.1.3

**Other mods installed**
AAI Containers & Warehouses 0.2.11
Warehousing Mod 0.5.7

**Comment by Deadlock989** [comment]
Also Dectorio concrete walls.

**Comment by Deadlock989** [comment]
While I'm digging in mod compatibility files. Dectorio decorative gravels were previously moved to mixers because of recipe category conflicts (#175). However 3.1.0 removed steam mixers, which means 3 of the 4 decorative gravels are unlocked in Crushing 1 but can't actually be crafted until electric mixers are unlocked in Crushing 2. The best way to handle this for the time being is to have them all unlocked at the same time with electric mixers, this isn't exactly great, but at least it respects IR3's "always able to craft new unlocks" requirement.
