### ISSUE TITLE
Planner buttons unavailable due to “construction robotics” technology requirement

### ISSUE THREAD

**Issue by Hawk777** [Deadlock989/IndustrialRevolution#283]
**Describe the issue**
When I open the menu of which buttons to show in the little box to the right of the inventory quick bars, Undo, Copy, Cut, Paste, Import string, Blueprint, Blueprint book, Deconstruction planner, and Upgrade planner are all greyed out and unselectable. If I hover over one of them, a tooltip says “This shortcut requires the Construction robotics technology.” I initially thought that maybe I needed more research, but there is no technology of that name, and I just recently obtained Industrial Roboports, so I figure it should be available by now.

I can use the keyboard shortcuts to create these planners, so this is not a huge problem, but it is a bit confusing and misleading.

**Factorio version, IR version**
Factorio: 1.1.87
IR initially: 3.0.18
IR upgraded today and problem still appears: 3.1.4

**Other mods installed**
* Black rubber belts 1.0.3
* Factorio library 0.12.9
* Larger lamps 1.5.1
* Recipe book 3.5.5
* Train control signals 1.0.6

**Comment by Deadlock989** [comment]
It shouldn't be possible to get into this state. The "Construction robotics" tech is not available in IR3, but the unlock state for these buttons is per player (not per game), so if you have unlocked these in any vanilla game or any other mod, they should also be unlocked in IR3. They are also automatically unlocked for every player that joins an IR3 game. I'm also surprised that you are apparently able to use these functions with the keyboard shortcuts but not the shortcut buttons - as far as I know, that also shouldn't be possible. I can't advise further without reproduction steps.

**Comment by Deadlock989** [comment]
Edited to add: by simply creating a new game, the shortcuts should be unlocked for you. Does that happen?

**Comment by Deadlock989** [comment]
In future versions of IR3, these planner-related shortcuts will simply have their unlocking technology requirement stripped from the prototypes, so they will always be unlocked as long as IR3 is installed. For players who never played vanilla long enough to unlock them (permanently across all games) by researching the unlocking techs, or who have reinstalled the game from scratch, or who have deleted their `player-data.json` for whatever reason, I suppose that the shortcuts will revert to being locked again once they uninstall IR3. There is no other way I can think of to handle this, given that:

- They can't be soft-unlocked by script because it turns out that only "custom" shortcuts (i.e. those with a Lua action) can have their unlock state changed by script, and these shortcuts are not that type
- They can't have the unlocking tech changed to an IR3 tech because there are multiple unconnected techs that need them to be unlocked and the prototype can only specify a singular unlocking tech

It's a weird set-up to be honest - I don't really get why they are locked at all, or why unlocking them is permanent across all games for that installation of Factorio, or why the unlocking trigger isn't a technology effect rather than a property of the shortcut itself, but that's all moot.

**Comment by Hawk777** [comment]
You’re right that, in effect, I haven’t played enough vanilla to unlock those buttons. I use a separate mutable state directory for each modpack so that I don’t have to go mucking around turning mods and off each time I load a save file; I just start Factorio from a separate shortcut for each modpack instead. Thus, within my IR3 install directory, I haven’t played *any* vanilla. So that explains it.
