### ISSUE TITLE
Can't put Chrome Plating Solution in Barrels.

### ISSUE THREAD

**Issue by excessi0n** [Deadlock989/IndustrialRevolution#289]
**Describe the issue**
Don't seem to be able to put Chrome Plating Solution in any containers; specifically looks like I should be able to barrel it but can't.
Sorry if I've missed something, just got to Chrome production.

**Factorio version, IR version**
Factorio: 1.1.80
IR3: 3.0.19

**Other mods installed**
none

**Comment by Deadlock989** [comment]
This is still the case in the 3.1.x versions (since July).

This was deliberate, although I have never been at ease with it. There are issues around menu space if you give every fluid in the game a barrel, so I set a maximum of one menu row (10 types) - I've put a lot of time into keeping the crafting menu tidy. I also didn't feel comfortable with putting metal plating solutions in a metal barrel - in my head, you'd end up with a chrome-plated barrel (in real life, acidic solutions are kept in glass, plastic or ceramic-lined containers; admittedly the mod still allows sulphuric acid in steel barrels).

I am going to mark this as "not an issue" for now but it's possible it may change in future.

**Comment by excessi0n** [comment]
Hi, thanks for the swift response. I can see the balance you're trying to strike and appreciate the nod to authenticity. For consistency with the other fluids and from a mechanic perspective; the place I'm making plating solution is likely to be some distance from where I'm making steel items (given the stage in the game you have to get to before you need plating solution) and it would be nice to be able to move the plating solution (one item) over to the steel items (many) without having to pipe it there. 

Thanks again for explaining your thought process and for putting so much energy into what I'm sure has been a massive undertaking. This is the first "conversion" mod I've played for Factorio and you appear to have set the standard extremely high. Not just with the logical consistency and balancing but also the finer details like intricate sounds and really very lovingly designed assets. 

Thanks for all the hard work, I'm havign a great time playing it.

**Comment by Deadlock989** [comment]
Re-opening this. I took a look at how it would pan out, thinking that maybe the recipes could be hidden from the player crafting menu and additional context given on the empty container tooltips instead. But actually, there is enough room on the tab for a whole new line of barrels without doing that, and it doesn't look bad if the row lengths are balanced out. Will likely include this in a future update.

**Comment by excessi0n** [comment]
That's great, thanks for looking into it. :)
