### ISSUE TITLE
Request to improve compatibility with remote configuration

### ISSUE THREAD

**Issue by Sipke82** [Deadlock989/IndustrialRevolution#292]
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/30873812/c5ef8320-55e0-442b-bc3a-70c8a3760b25)

**Comment by tburrows13** [comment]
Hello, Remote Configuration author here (Xorimuth).

The idea of RC is that the player is able to do things like setting combinators from the map view at any distance, even though item transfer from such distances is prohibited. Something like the Shift + E toggle here would fall under the category of things that RC should be able to enable, but obviously since it is a scripted effect, I can't.

This could be fixed by you adding a remote interface to allow other mods to trigger the toggle, but to be honest, I'm not really interested in implementing the compatibility for that to work on my side either, so I'd say don't bother.

If you want to, you could change it so that it skips the 'is player in range check' when Remote Configuration mod is active - up to you if you feel that is outside the scope of IR3, as it does feel a bit silly.

**Comment by Deadlock989** [comment]
It wouldn't be difficult - just replacing the current `player.can_reach_entity()` checks with a value that also checks for the presence of RC - but I feel like I am flying a little blind here as I have no idea what the consequences might be, being unfamiliar with RC. Most likely it would be fine but I don't actually know.

Entity toggles fall into a few categories:

- A few already work outside of player reach - this includes things like toggling constant combinator on/off state and toggling trains between automatic and manual, i.e. things that can already be done in the base game from beyond player reach, just with more mouse clicks.
- There are currently two cases where the target is a locked assembling machine which gets its recipe toggled between one of two states (steel boilers and geothermal exchangers). Changing recipes can't usually be done from beyond player reach (either by opening the GUI or copy-pasting a recipe). Is this something RC enables?
- The remainder of the toggles swap the entity with a duplicate, in order to effectively change some property or behaviour that can't usually be changed at runtime, e.g. the photonic cannon firing arc and barrelling machine behaviours referenced above. I can't think of any problems here. Note to self: this kind of toggle correctly checks that the toggler is on the same or a friendly force, but the recipe toggles above do not, should fix.

**Comment by tburrows13** [comment]
> Changing recipes can't usually be done from beyond player reach (either by opening the GUI or copy-pasting a recipe). Is this something RC enables?

It can be done in vanilla, but it requires creating a blueprint (or copy-paste temporary blueprint) and placing the blueprinted machine of the new recipe on top of the faraway machine. RC allows you to just open the machine and change the recipe (this does come with the unfortunate side-effect of returning the in-progress items to the player's inventory across the long-distance. RC can usually detect this and instead drop them around the machine, but there are some caveats where it can't do that. This is the only known item-transfer 'exploit' in RC.)

> The remainder of the toggles swap the entity with a duplicate, in order to effectively change some property or behaviour that can't usually be changed at runtime, e.g. the photonic cannon firing arc and barrelling machine behaviours referenced above. I can't think of any problems here. 

Yeah, those are the sorts of things that RC would enable to happen at any range if it could.

The general philosophy of RC is that it allows you to directly do things that you can already do in vanilla, but without the blueprint 'workarounds' that vanilla requires.

**Comment by Deadlock989** [comment]
> It can be done in vanilla, but it requires creating a blueprint (or copy-paste temporary blueprint) and placing the blueprinted machine of the new recipe on top of the faraway machine.

I didn't know that. Blueprints strike again (cough circuit wires cough). 

I'll take a look at this soon. Either I'll check for RC or I might just remove player reach regardless, or somewhere in between.

**Comment by Deadlock989** [comment]
For the next version:

- All hotkey actions require the entity to belong to a friendly force.
- Steel boiler and geothermal exchange toggles do not require player reach.
- If RC is installed, all other toggle hotkey actions except inventory transfers do not require player reach.
