### ISSUE TITLE
One of my belt lines haves infinite amount of sulphur at the end of it.

### ISSUE THREAD

**Issue by Maltsi** [Deadlock989/IndustrialRevolution#306]
**Describe the issue**
One of my belt lines haves infinite amount of sulphur at the end of it. Its always the last belt on that particular line, meaning that if i build it longer, the bugged belt will move too. Inserters taking sulphur from that piece will ignore limits on assemblers and they get stuck eventually trying to add more and more of it. Belt is shared with coke, but that is not unlimited or bugged in anyway. I cannot deconstruct it with bots since it contains unlimited amount of sulphur, i can manually pick it up, but the entire map will be filled with sulphur. and building it back will bug it again. Only fix seems to be to blow it up and then build it back.

This is what happens if i manually remove it, all of that yellow is sulphur.
![20231004163651_1](https://github.com/Deadlock989/IndustrialRevolution/assets/146978009/36795fb7-2e09-4c34-81c0-54c9d036d42b)

This particular line left of me is the one with a bug.
![20231004163703_1](https://github.com/Deadlock989/IndustrialRevolution/assets/146978009/27c616e8-d9a5-469e-8e5f-5c834cce2d02)

Possibly cause for this is that when i copied this above sulphur production line (red circle) and pasted it below (green circle), my friend got desynced and from that point forward hes getting regular desyncs when we are near this bugged belt (blue circle).

![20231004193748_1](https://github.com/Deadlock989/IndustrialRevolution/assets/146978009/dee55622-0f37-4d40-bb7d-54e68cb0f54d)

**To Replicate**
load the save i provided and mine the last belt below the player or just pick up stuff from the last belt, it will never end.

**Factorio version, IR version**
Factorio 1.1.91
IR 3.1.8

**Other mods installed**
Full mod list.

Additional paste settings (fixed)
Black Rubber Belts
Cybersyn combinator
Factorio Library
Factory Planner
Factory Search
GUI Unifyer
IR 3 and all 4 asset packs
IR 3 Deep space mining
IR 3 Powered Loaders & Ingot Stacking
Logistic Request manager (continued)
Module Inserter extented
Ore manager fixed
P.U.M.P
Project Cybersyn
Rate Calculator
Recipe Book
Solar Calculator

Logs (hopefully right one)
[factorio-current.log](https://github.com/Deadlock989/IndustrialRevolution/files/12806119/factorio-current.log)

Save File
[IR3 - 3 backup.zip](https://github.com/Deadlock989/IndustrialRevolution/files/12806124/IR3.-.3.backup.zip)

**Comment by Deadlock989** [comment]
This is very unusual, I've never seen anything like it before. I can confirm that with the save file, the belt segment explodes into just short of 4.2 million sulphur pieces on the ground if you pick it up, which freezes the game for several seconds. This happens even with no mods installed.

Using the API to look at the contents of the belt, `get_transport_line(2).get_item_count()` returns the same value, 4193832. This is suspiciously close to 2^22, just 472 short. 

However I'm very doubtful that this is anything to do with IR3. There is no scripting in the mod for copy-pasting anything other than transmats, and the mod does nothing special with belts at all. I wouldn't even know how to get a belt transport line into such a state.

If you don't care about losing achievements, you can destroy the broken belt segment more safely if the host highlights it with the cursor and runs this command:

/c game.player.selected.destroy()

I also tried using the built-in editor to delete it but on my system that seemed to lock Factorio up permanently.

Otherwise, you could try reporting this on the official Factorio forum, either as a bug or in the "technical help" section, someone there might be able to shed some light. But my gut instinct is that this is a bit-flip or some other randomness.

**Comment by Deadlock989** [comment]
Noted from official forum thread: this turned out not to be an issue with the belt or the belt's transport line data, but most likely a bit flip in the item stack itself, so that one specific sulphur item on the belt had a stack size of 4.2 million.
