### ISSUE TITLE
A couple of issues with building rotation

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#308]
**Describe the issue**
A couple of issues noticed in sandbox mode.

issue 1

When I take the Geothermal exchanger from inventory, I cannot rotate it with the R key. It can only be rotated after it is installed.

If I rotate the installed Geothermal exchanger, hover over it and press Q, the Geothermal exchanger is automatically taken from inventory as it should, but the direction is not saved.

issue 2

Inconsistency between Electric boiler and Copper boiler. I cannot swap the input and output of an installed Electric boiler with the R key, while it is possible to do so with an installed Copper boiler, which has a similar shape.

**Factorio version, IR version**
Factorio 1.1.91 
IR3 3.1.8

**Comment by Deadlock989** [comment]
It's easier for me track and resolve unrelated issues if they are reported separately.

Both parts of issue 1 are fixed for the next version. The entity concerned was set to not display fluid boxes when no fluid recipe is selected (`off_when_no_fluid_recipe = true` in the fluid box properties), and assembling machines with no active fluid boxes cannot rotate. Originally, the exchanger only had one fixed recipe, so this behaviour was overridden by the existence of the `fixed_recipe` property which effectively enabled the fluid boxes, but when this property was removed for the addition of the additional hot water recipe in version 3.1.0, the fluid box property was not updated to preserve the original behaviour.

Issue 2 is not fixable by mods. Copper boilers behave similarly to the vanilla "iron" boiler because they are both boiler-type entities. Real boilers cannot have an electric power source so the electric "boiler" has to be an assembling machine type entity locked to specific recipes. The game has different hard-coded treatments for different entities regarding the way it handles rotation and flipping with non-square collision boxes, and these behaviours are not accessible to modders at all.

**Comment by Bilka2** [comment]
> Real boilers cannot have an electric power source

They can have any energy source as far as I'm aware. If the electric energy source doesn't work for some reason, that sounds like a candidate for a base game bug report.

**Comment by Deadlock989** [comment]
I don't recall what the difficulties with an electric energy source for the original attempt at the boiler were, but I note that at least one other popular mod has also opted for a crafting machine solution. I don't have the time or motivation to retrace my steps there. At any rate the point is moot because the crafting machine version I went with for 3.1.0 allows for two toggleable "modes" (i.e. recipes), steam and 90°C water, and that's impossible with a true boiler. The only disadvantage is that non-square crafting machines don't have the nice 180° degree rotation behaviour that boilers and generators have, but there's nothing I can do about that and it's a minor inconsistency that can easily be worked around.
