### ISSUE TITLE
laboratory upgrade planner

### ISSUE THREAD

**Issue by Quezler** [Deadlock989/IndustrialRevolution#31]
the upgrade planner does not upgrade the steam labs to iron labs by default, possibly missing the `next_upgrade` property:

![Screen Shot 2021-03-09 at 17 19 21](https://user-images.githubusercontent.com/3179271/110502634-a9de5900-80fb-11eb-9a76-5b03430c5ef1.png)

**Comment by Deadlock989** [comment]
Needy upgrade planner strikes again. There are several of these steam-to-electric upgrade issues that I never bothered with because their power supply needs are so different that there's a lot more involved in upgrading from steam than just swiping over them with an upgrade planner. But I will change it.

More of an issue is that the "decorative fake lab" used in the main menu simulation is appearing in the entity upgrade picker.
