### ISSUE TITLE
Almost no point in using Heavy Roller / Picket

### ISSUE THREAD

**Issue by Sipke82** [Deadlock989/IndustrialRevolution#315]
Perhaps its me, but from my perspective there is almost need to use the heavy Roller/Picket. 

After reading this recent [reddit post](https://www.reddit.com/r/factorio/comments/17gxkae/huge_player_inventory/?sort=new), it made me realize that its a more general Factorio "problem". the large stack sizes of factory building blocks, such as assemblers and inserters etc, makes the use of "supply" vehicles unnecessary. Perhaps it would be a good mind experiment how the game would be if those factory building blocks would have lower stack sizes. so you actually need the Large inventory sizes of the Heavy roller/picket?

Because now, we can just carry all of the factory building blocks in our backpack. Consequently bypassing this logistical challenge.

Curious to know what your thoughts are.

**Comment by Deadlock989** [comment]
My thoughts are as follows:

- Heavy rollers (early game vehicle) can fit many more roboports than early-game armour can (e.g. over 3x the amount handled by bronze armour), so they can deploy many more construction robots than you can at that stage of technology, allowing things to get built half an order of magnitude quicker. Even if they didn't have as many grid slots, the bots can be deployed simultaneously with your own. In the very late game, heavy pickets scale that even further if you need to build an output beyond your main logistic zone range.
- Heavy pickets can cross water.
- Inventory management is the second most tedious aspect of Factorio and if you needed to manually carry 80 stacks of iron ore from a distant output because of terrain RNG, you would need to clear that inventory space first. If you have a vehicle dedicated to it and use the inventory transfer hotkey or set up delivery plates appropriately, you don't even need to think about it.
- Not everything needs to have a huge need. Nor should anything be compulsory.
- Steam-driven bulldozers on caterpillar tracks are fucking awesome.
