### ISSUE TITLE
Liquified gases question, feature or bug?

### ISSUE THREAD

**Issue by rivaroska** [Deadlock989/IndustrialRevolution#321]
**Describe the issue**
If I place a gas vent on my containers or any pipe that contains liquid nitrogen , helium or oxygen ,they will be vented by the device which is strange because description reads "Release GASES onto the atmosphere" not liquids , and I tried with other liquified substances such as petrol, water , sulfuric acid and it didnt work on those , as it shouldnt. 
Is that supposed to happen or is it a bug?

Thank you for your time and I really like your mod. It taught me how to use red and green circuits which I hadnt touched before because I thought they had extremely specific uses (and I had over 2000 hours into the game up until that point) and now I find the incredibly useful.

**Factorio version, IR version**
Factorio version : 1.1.94 
Industrial revolution 3.1.8

**Other mods installed**
All other modsa are small QOL  so I dont think they matter

**Comment by Deadlock989** [comment]
It's intentional. The idea is that cryogenic gases boil very quickly on release into warm air, so they basically turn straight back into gas and are vented.

The Manifesto page about spills and venting has had its wording clarified for the next version, and it specifically mentions liquified gases as an exception.
