### ISSUE TITLE
Reduce electroplater fluidbox size

### ISSUE THREAD

**Issue by Kaimdrol** [Deadlock989/IndustrialRevolution#329]
**Describe the issue**
Electroplaters can store up to 1000 of the electroplating fluid, when recipes use only 10 of each fluid.
This creates huge wasted buffers of expensive eletroplating fluid.
I suggest reducing the fluidbox to 100.

**Factorio version, IR version**
Factorio 1.1.94, IR3 3.1.9

**Other mods installed**
Only QOL mods.

**Comment by Kaimdrol** [comment]
- Electric boilers and polluted water cleaners store 1000 water/steam in their output, but that's just inexpensive water. Copper boilers are limited to 200.
- Electric mixers and advanced mixers can store up to 1000 liquid concrete
- Ambient heat exchangers, cryogenic plants, air compressor store up to 1000 fluid in their output
- Geothermal exchangers seems to to go 1000 in the stats but I haven't used them so I don't really know.
- Petrochemical generators store 200 fuel but consume at most 2/s

That's all I got for now.

**Comment by Deadlock989** [comment]
I ran a scripted validation check on all assembler and furnace type entities with fluid boxes. There are numerous ones with input or output boxes with 1000 capacity (base area 10). So I have a comprehensive list.

However, double checking vanilla, this is how they are set up there as well. Assemblers 2 and 3, chemical plants, pumpjacks and the oil refinery all have 1000 capacity for either input or output or both. If there are other crafting machines with fluid boxes in vanilla I don't recall them (I haven't played vanilla since 0.17).

I am going to think about this again later. Output is certainly less of a problem and the machine needs some capacity to "back up". But input is different, especially if the fluid is costly. But it's also noteworthy that a single piece of pipe stores 100 fluid and you might run at least tens of pipes to a production centre, at which point another 10 pipes worth doesn't seem like a big deal.

**Comment by Kaimdrol** [comment]
Yes but all those only store a few times the recipe inputs or outputs unless you force-feed them as the player. 
Laser assemblers have a 1000 fluidbox too but stop with a "output full" well before that, as will refineries.

The machines I listed _felt_ oversized to me. It's a personal feeling, and quite minor too.  
Having 14k chrome plating solution stored in machines is nothing compared to the 7.4 million I used until now.

**Comment by Deadlock989** [comment]
On further investigation it seems the issue is the entity type. Entities based on `assembling-machine` (assemblers obviously, but also vanilla's chemical plant and oil refinery) apply the recipe-based input/output limits, so e.g. an assembler crafting steel motors will stop at 20 input lubricant despite having a fluid box capacity of 1000. Entities based on the `furnace` prototype however (including IR3 electroplaters) seem perfectly happy to use the entire fluid box and don't have any concept of a recipe limit, just as vanilla furnaces are happy to fill the entire output slot with a full stack - but crucially there are no fluid-handling furnace-type entities in vanilla. Running the script check on furnace-types only narrows the offenders down to these IR3 machines:

- Electroplater
- Metal casts
- Ambient heat exchanger
- Barrelling machines

The ore washer is in this category for example but it has had its boxes limited to 100. The electroplater should probably follow this example as it has exactly the same kind of pass-through set-up as the ore washer. The remaining three machines are all 1x1 so they should definitely be limited as well.

**Comment by Kaimdrol** [comment]
Thanks for the update and the great mod !
