### ISSUE TITLE
Battery Charger input buffer seems higher than necessary. 

### ISSUE THREAD

**Issue by ajklotz** [Deadlock989/IndustrialRevolution#332]
**Describe the issue**
I created a little sub factory to generated charged batteries. My two battery assemblers can feed about 8 battery chargers. I noticed that they took a very long time to start working together, and I noticed that the input buffer for the charger is 50 batteries. Shouldn't this be less than a handful instead?

**Factorio version, IR version**
1.1.96 and the IR 3.1.11

**Other mods installed**
n/a

**Comment by Deadlock989** [comment]
Technical note: this "buffering" behaviour is set on recipes, not on machines; is referred to as an "overload multiplier".

Looking at the code I can see that all three charging recipes have an overload multiplier of 50. In the case of the electric batteries, this has been in place for something like 4 years, and the hydrogen cells inherited it when they came later. No other IR3 recipe does it. So I feel like this wasn't a random decision and was done deliberately, but it's so long ago I have forgotten what that was all about.

Is it really a problem?

**Comment by Deadlock989** [comment]
I want to improve the battery charger sprites at some point and I was thinking about making charger recipes batched (4x input, 4x output, 4x time) so that the machine shows multiple smaller batteries being charged rather than one enormous one. I will make a decision either way about removing the overload multiplier then. This won't happen for a while most likely.

**Comment by Deadlock989** [comment]
I'm not going to get to the sprites for some time so I have gone ahead and removed the overload multiplier for the next version.
