### ISSUE TITLE
Not an issue, suggestion/idea for air purification

### ISSUE THREAD

**Issue by ajklotz** [Deadlock989/IndustrialRevolution#336]
**Describe the issue**
It would be nice to be able to measure pollution so we could control the consumption rate of air filters in air purifiers. Right now, the air purifiers ran at full throttle when things are settled down in the factory. I would like to reduce the wasted air filters when air pollution is not a problem in the chunk it is in. 

**Factorio version, IR version**
1.1.97    IR 3.1.11

**Comment by Deadlock989** [comment]
It would be nice, but unfortunately there is no direct API hook that would allow this to happen efficiently, leaving you with the option of constant polling by scripts. To keep UPS from being eaten up by this, you would have to limit the number of scripted entities being polled per interval, which means that the more of the scripted entity you have, the less frequently each can update. IR3's forestries work on this kind of basis, but their cycle is extremely slow (spread over a few minutes) compared to the rapid polling (seconds or less) combinator-type entities are usually assumed to need.

There are already some implementations of this kind of thing on the mod portal (e.g. Pollution Combinator, Pollution Detector, probably others) - I can't recommend any of them because I haven't tried them, but it's probable that some are more UPS-friendly than others.

**Comment by Deadlock989** [comment]
I don't mind reading suggestions but haven't asked for them and can't guarantee a reply. This tracker was set up to get bugs fixed.
