### ISSUE TITLE
Water in output stalled ore washers unstable

### ISSUE THREAD

**Issue by shysteph** [Deadlock989/IndustrialRevolution#345]
**Describe the issue**
Water amounts in ore crusher machines that have full output varies wildly and changes the total amount of water in the system instead of balancing out and stabilizing. Even if I put buffer tanks at the far end or use one way valves the amounts still bounce inside the crushers.  See attached save file where I am standing next to the impacted ore washers.

**Factorio version, IR version**
Factorio: 1.1.94 steam
IR: 3.1.12

**Other mods installed**
Only other non qol mods are the deeadlock989 mods recommended in the documentation (black belts (looks super good fyi), lighting, stackers, space thing).

**Comment by Deadlock989** [comment]
There is no save file attached.

This just sounds like regular fluid system oscillation to me. What is the problem?

**Comment by shysteph** [comment]
[ggg.zip](https://github.com/Deadlock989/IndustrialRevolution/files/13533269/ggg.zip)
It oscillates really rapidly, draining a full tank to zero in seconds sometimes or filling one up equally fast.  With the washers idle they should just work and look like normal pipes right or like a boiler passing through water?

**Comment by Deadlock989** [comment]
I can't see anything particularly unusual here but no, washing plants and boilers don't behave exactly like pipes because they are configured differently. The input-output water fluidboxes in washing plants are set up in exactly the same way as vanilla boilers ("iron boilers" in IR3) except that their base area is currently half the size of boilers. If you set up a line of iron boilers you will see similar behaviour except that the oscillation is not as pronounced because their base area is twice the size, so they are less sensitive than washers to sudden changes in base level. Input-output fluidboxes on machines such as boilers and washing plants have a higher "height" and lower "base level" than simple transport fluidboxes, see Fluidbox B in [this diagram](https://lua-api.factorio.com/latest/types/FluidBox.html). Fluidboxes configured like that (base area N/2, height 2, base level -1) will fill up to half of their height before passing water on to a neighbour with base level 0; but any water in the top half can slosh around freely back and forth between neighbouring fluidboxes if they have base level 0 or if they have base level -1 and are also filled up to halfway. Sorry if this is confusing and I probably haven't described it very well but this is how Factorio fluid systems were made and modders can't change the way it works.

The root cause of this behaviour in your set-up is the circuit-controlled pump you have to the south which is effectively voiding water (by boiling it to steam and then venting it) when the attached tank has more than 11k fluid in it. This is creating a cycle where once the threshold is reached, the top level of the whole fluid system is lowered quite rapidly, and the small but tall fluidboxes in the washing machines have their excess (the part over half their height) immediately redistributed. I'm not sure why you are doing this, it seems expensive and wasteful and unnecessary. When this overflow pump is removed or disabled, the "sloshing" behaviour goes away. (Please note that I can't get into gameplay help topics here, it's just a bug tracker.)

But to be honest - I don't see this is as a problem particularly, it doesn't have any negative effect on operations, the washers are getting enough water to operate either way. The only thing I can do here would be to double the fluidbox size in washers so that they are exactly the same as vanilla boilers - likesay, this won't make the behaviour go away, it would just be less pronounced. But I need a reason to make changes like this.
