### ISSUE TITLE
Air pipe and machines

### ISSUE THREAD

**Issue by mussii** [Deadlock989/IndustrialRevolution#346]
**Describe the issue**
There are machines that _seem_ to fit an air pipe for some recipes but air pipes can't be connected to them since they can only transport Compressed Air. 

I'll show some examples. Steel foam requires Nitrogen Gas, the furnace automatically displays the _air pipe_ connection. This behaviour seems to be inconsistent, in the other example, the beam laser recipe requires Helium gas but the assembler displays the "normal" pipe. 

![imagen](https://github.com/Deadlock989/IndustrialRevolution/assets/27778442/203df214-12f1-4cc5-8c79-befd8c6a8afa)

Suggestion: Make the connections on the machine consistent and use the air pipe template when using gases ( it looks awesome ) and let the air pipe carry all kind of gases. 

It is a super minor thing and your time will probably be more useful spent on other endeavours. 

IR3 Version: 3.1.12

**Comment by Deadlock989** [comment]
It is inconsistent and it does niggle at me very slightly. I have tried to improve it from time to time (e.g. #243) but there are some insurmountable issues with it all. 

The main issue is that pipes cannot filter for multiple fluids (see #148). You can have pipes restricted to exactly one fluid, or they can carry all fluids; there are no other options. There is part of me still hoping that this will change one day because I really want specialist molten metal pipes, and several modders have asked for the ability to have multiple filters on pipes or any other fluidbox, but as things stand, Wube are on record as saying there are no plans to change it because of concerns about performance - it took a long time and a lot of back-and-forth even to get one filter. In the most recent blog posts, it also seems as though Wube have "borrowed" the modding community's ideas about foundries and molten metals but their foundry is clearly displayed as using regular iron pipes so there's no evidence that this is going to change when the DLC eventually drops (IR3 will not be compatible with the DLC).

The other is that machine pipe covers are fixed definitions, they can't be made to respond to changes in recipe. This creates a fundamental issue for assembler-type entities (where you choose a recipe) that can handle a range of fluids if you have also tried to have different types of pipe that carry different types of fluid. Basically the problem here is one that most overhaul modders run into at some point: Factorio is built in a way that assumes some entity types are unique (pipes are one example, another is rails) but allow you to go ahead and create multiple types anyway. In some ways it was probably a mistake on my part to add air pipes in the first place.

I will take a look at the way the electric alloy furnace is set up but this is a low priority issue and my gut instinct is that it can't be improved by much or at all.

**Comment by Deadlock989** [comment]
Changes for the next version.

Electric alloy furnace: only has one fluid recipe (steel foam), which has nitrogen as an input. The machine is set up with an output fluidbox as well but currently no recipe uses it. The pipe covers have been changed to the iron pipe cover.

Blast furnace: all blast furnace recipes have compressed air input, so the input-output air pipe covers are correct; the output is always carbon dioxide, so the output fluidbox has been changed to the iron pipe cover.

Air compressor: has the correct air pipe cover.

The only other machines that handle compressed air are the cryogenic plant and the gas vent, but they both also have elemental gases as possible inputs. The machines currently use the generic pipe cover which is the least worst option, so no change.
