### ISSUE TITLE
Top-up/Overflow Options for Valves

### ISSUE THREAD

**Issue by AlexSiemers** [Deadlock989/IndustrialRevolution#352]
I was wondering if it would be possible to make valves work like they do in Angel's mods where you can set them to allow flow through with a threshold of fluid being crossed on one side or the other. Not only are there enough cases for top-up and overflow valves here for this to be convenient over having to connect pumps to buffer tanks (with more fluid byproducts and secondary use cases), it would also make valves much more useful since avoiding backwash doesn't seem like an issue that matters in general with Factorio.

**Comment by Deadlock989** [comment]
I'm not familiar with Angel's valves but I'm aware of the general concept from the [Advanced Fluid Handling](https://mods.factorio.com/mod/underground-pipe-pack) mod (which I contributed graphics to but never got a credit for). I've never tested out AFH with IR3 (it's a bit over-complicated for my tastes). It uses a similar method to IR3's entity toggle hotkey where selecting a valve with the mouse and then hitting Num+/- swaps the valve entity out for one with increased/reduced base level. Is that what you mean? 

If it is, then yes, it's certainly possible, but it would take some work, including graphics work. I'm not sure what it would really add to the mod other than avoiding the need to use circuit-controlled pumps occasionally? Overflow valves I can see the utility of (but as you say, you can make one yourself with a pump and a buffer tank), while underflow valves in particular are not a thing I've ever had cause to wish I had in one tile.

You're right that the current valves are not particularly necessary - I find myself using the steam ones quite often since it's nice to isolate sections of early game steam malls and avoid having it all slosh back and forth semi-randomly, but it's not a game changer.

**Comment by Deadlock989** [comment]
I looked into this some more. It's a bit of hack in some ways. Overflow valves work by setting their input fluidbox base level to (e.g.) 0.8 for an 80% threshold and assume that the output fluidbox feeding them has base level 0 and height 1 (which is the case for vanilla storage tanks and pipes). This means the feeding fluidbox has to get to at least 80% full before any of the contents can pass into the valve. But it would only work well if the feeding fluidbox has a much bigger capacity than the valve, because the amount that can flow through at once is capped at 20% of that capacity - so if you have an overflow valve between two regular pipes, the throughput is going to be _significantly_ lower than a line of plain pipes would be. However with a large enough capacity (minimum 5x the valve's capacity, which would include IR3 small tanks) you would get decent throughput. 

The same is true for underflow valves except the other way around, so they would only work well when feeding a larger tank. Attaching one to the input pipe of a crafting machine in particular is unlikely to function as desired, since most (if not all) crafting machine input fluidboxes have a base level of -1. It would also be impossible to completely empty the valve. To be honest, I'm not sure exactly what utility these even have.

I don't know if there is some magic reason for choosing 80% - both Angel's and the Flow Control mod seem to have chosen this value, while AFH gives you granular control at intervals of 10%. Perhaps because vanilla storage tanks are 25k so with the 80% threshold they would overflow at exactly 20k.

Anyway, I'm interested in the overflow valves because I can see it would be useful for the pre-electronics era of IR3, and code-wise it would be pretty simple to implement because of the existing toggle hotkey code, but the real issue is graphically distinguishing the three valve types. If I get any inspiration I'll do this.

**Comment by Deadlock989** [comment]
I've implemented this in the next version of IR3 for all four pipe types (the entity toggle key will switch a valve between current behaviour, overflop and top-up modes) but I have to say I find it a bit underwhelming and objectively worse than using circuit-controlled pumps. If you set up a storage tank (large or small) -> overflow valve -> pipes, the pipes won't ever be filled beyond about 85% +/- 5% (the exact amount is chaotic), so overflow and top-up valves will always have a lower max throughput than pipes do. That said, they could come in handy if you don't have circuits or pumps yet. I have also added circuit network connections to all three valve variants. The valve mode is indicated by an additional green mark on the valve for overflow, red for top-up.
