### ISSUE TITLE
Airships Alpha (0.1.0) - Airships can't cross larger bodies of water

### ISSUE THREAD

**Issue by Keriew** [Deadlock989/IndustrialRevolution#359]
**Describe the issue**
As flying machines and per their description, I expected airships to freely be able to cross the water (like heavy picket). It seems to be work fine for smaller bodies of water, but those that are bigger, starting at those approximately slightly larger than a chunk are uncrossable - the airship seems to be tethered to the nearest land refusing to move past some distance from the land, and if attempts to move are stopped, it will slowly slide back to the nearest land. The behaviour is the same for both hydrogen and helium airships.

I imagine this is inherited from Spidertron behaviour, which tries to place the invisible airship legs on the land and prevents the airship from moving too far from land.

**Factorio version, IR version**
Factorio: 1.1.100
IR3: 3.1.14
IR3 Airships: 0.1.0
IR3 Assets 1: 1.1.7
IR3 Assets 2: 1.1.1
IR3 Assets 3: 1.1.6
IR3 Assets 4: 1.1.0

**Other mods installed**
No other mods.

**Comment by Deadlock989** [comment]
You were right to expect this because airship's invisible legs are supposed to end up with a collision mask that allows water crossing, but due to a last minute change to the add-on's dependencies just before I published it on Christmas Eve, this isn't guaranteed to be set up properly. I'll need to fiddle with both IR3 and the add-on to get this fixed properly but in the meantime you can hotfix it for yourself by opening the Airships mod's `info.json` file and changing the line that currently reads:

```	  "~IndustrialRevolution3 >= 3.1.14"```

to

```	  "?IndustrialRevolution3 >= 3.1.14"```

i.e. change the tilde ~ to a question mark ?.
