### ISSUE TITLE
Molten glass - missing recipe?

### ISSUE THREAD

**Issue by xykite** [Deadlock989/IndustrialRevolution#36]
The arc furnace doesn't have a recipe for "molten tin + silica -> molten glass" (but it does have "molten iron + carbon -> carbon steel" which looks like the same pattern). Is this intentional?

**Comment by Deadlock989** [comment]
The "plan" was that carbon would be the only solid ingredient that could be used for molten alloying because molten carbon is impossible in normal terrestrial conditions - glass is treated as an alloy internally, which has already caused issues (see changelog for 2.0.5). Molten glass was tacked on last of all, almost as an afterthought, without thinking about it carefully enough - it required some bending of the internal rules which produce these arc furnace recipes. 

Tin melts very easily, at a much lower temperature than sand. In the real world, molten tin isn't ever mixed with molten silica as far as I'm aware. It is used in making "float glass" but as a reusable "bed", not an actual ingredient. Molten glass in IR2 already pushes the credibility of what can and should be made in an electric arc furnace - not that I'm too bothered about realism and this doesn't bother me anywhere near as much as the issues it created by forcing IR's alloy system to handle it. In hindsight I think it was a mistake to include it at all. However I don't want to remove it because the mod is "done" and I don't want to break existing saved games.
