### ISSUE TITLE
Last update broke Balanced Waterfill compatibility

### ISSUE THREAD

**Issue by LCStark** [Deadlock989/IndustrialRevolution#365]
I've been playing IR3 with several other mods, including Balanced Waterfill (https://mods.factorio.com/mod/balanced-waterfill) and it's been working fine for quite some time. Last IR3 update changed something with collision layers, because now I can't place mining drills on resources and my vehicles collide with resource fields.

![ir3](https://github.com/Deadlock989/IndustrialRevolution/assets/166645/75ebf125-f26c-4271-9a4e-931ab34ee4d5)

It is a problem related to Balanced Waterfill mod, as disabling it fixes the issue.

I'm playing Factorio version 1.1.100 and IR3 version 3.1.15.

**Comment by Deadlock989** [comment]
This is due to an oversight in 3.1.15 - it turns out that the Factorio core Lua library function `get_first_unused_layer()` (used by both IR3 and Balanced Waterfill) is only effective if the new layer is actually assigned to an entity within the same data stage by the same mod. In 3.1.15 the function is called earlier in the loading process than before (so that IR3 heavy pickets and airships from the Airships add-on can both use the same water-crossable mask) but as it is still not assigned to any entities until later, it is leading Better Waterfill to think that the mask is unused. I will have to rearrange the living room furniture again.

**Comment by Deadlock989** [comment]
This is fixed for the next version (to be released in the next few days, maybe tomorrow). I have briefly tested it with Balanced Waterfill and after the fix had no issues with placing electric drills on coal or driving a car over resources - if you encounter further issues after 3.1.16 is released please open a new issue.

**Comment by LCStark** [comment]
Will do, thanks! And thank you for the detailed explanation of the cause.

**Comment by MagicManMe** [comment]
Hey sorry, have been without internet for a bit. Yep! you were completely right, updated and completely fixed thank you!! <3
