### ISSUE TITLE
[Powered Loaders & Ingot Stacking] Mod crashes on ingot stack unstacking from cursor when inventory is full

### ISSUE THREAD

**Issue by LCStark** [Deadlock989/IndustrialRevolution#367]
All my inventory slots are filled and I carry an additional stack of ingots in the cursor. When I accidentally left-click on the ground, the cursor stack tries to unstack. From what I see in the code, in such case it should spill the ingots on the ground, but instead the game crashes with an error:
![ir3_2](https://github.com/Deadlock989/IndustrialRevolution/assets/166645/2c1a2695-a239-4c32-9fe6-728187a22d43)

Factorio v.1.1.100, IR v.3.1.15 and 3.1.16

**Comment by Deadlock989** [comment]
Thanks for the report. I don't know what happened there, the code was just plain wrong - I think it is left over from an earlier version and didn't get updated. Fixed for next version of PL&IS.

**Comment by Deadlock989** [comment]
Actually I'm going to rewrite this. Item spilling doesn't often happen because the "density" of stacked ingots is the same as normal ingots, so they take up the same number of slots. The code was mainly there as a contingency in case some other mod messes with stack sizes. However I now realise that of course it is possible to have a full inventory and then pick up more stacked ingots from somewhere else. The better approach would be to put the unstacked ingots into the cursor stack rather than try and find inventory space for them.
