### ISSUE TITLE
Photonic cannon locks on out-of-range stationary entities

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#369]
The photonic cannon becomes non-functional when an unmovable entity, such as a worm or nest, is close enough for it to track it, but far enough where it can't shoot at it. The cannon will remain in this state indefinitely, ignoring both mobile entities and new, closer in-range, non-movable entities.

You can test this yourself by doing the following steps:

- Create a debug world
- Create a small worm
- Create a photonic cannon just outside its range to the worm
- Power the cannon
- Spawn a small spitter outside of the cannon's range
- Aggro the spitter into the cannon's range
- Observe the cannon never will break lock on the worm

**Factorio version, IR version**
1.1.101, 3.1.16

**Other mods installed**
Only IR mods

**Comment by Deadlock989** [comment]
IR3 doesn't have a plasma turret. Do you mean the photonic cannon or the arc turret?

**Comment by doktorstick** [comment]
Hah, sorry, yeah, the photonic cannon.

**Comment by Deadlock989** [comment]
I can't investigate this just now but it is likely due to a change a couple of months back in 3.1.9 whereby photonic and arc turrets now always prioritise enemies with more health. Arc turrets shouldn't have this issue however as they are also set up to ignore non-moving entities.

If I can reproduce it then the options here would be:

- Revert the 3.1.9 changes
- Make photonic cannons also ignore non-moving entities (would fix this issue but make them useless for taking out nests)
- Reduce tracking range of cannons to the same distance as firing range (meaning they would waste some time while they go through the "prepare" stage when a moving enemy comes into range)

**Comment by doktorstick** [comment]
I don't like the second bullet as this renders them ineffective against worm/nest creep, which is a feature of the Rampant AI mod (the sieging mechanic). That's how I noticed, by the way.

Is it possible to do 1-2 passes whenever the turret needs to pick a new lock? First pass, filters for mobile entities only out to tracking range. If none available, perform a second pass filtering for all but limited to cannon range?

**Comment by Deadlock989** [comment]
It's not possible to do passes. The actual target choice function is not exposed to the API; you can influence how turrets behave with a handful of properties, some of which are mutually exclusive (preferring higher health / minimal turn), some of which are based on target masks applied to the enemy entities (which are annoying to use because they are ignored by personal defence equipment turrets).

At the moment I'm tilting towards removing the extra tracking range but extending the turret's range very slightly to compensate, will decide in the New Year.

**Comment by Deadlock989** [comment]
I looked at this and decided to remove the photonic cannon's high health target preference that was added in 3.1.9 as this was the root cause of the issue. The behaviour was left intact for arc turrets as they will never target worms/nests.
