### ISSUE TITLE
dectorio exploding trees

### ISSUE THREAD

**Issue by SilverDeath32** [Deadlock989/IndustrialRevolution#37]
hi,

first, big thanks for creating and maintaining this great mod.
with dectorio and ir2 installed (and nothing else) trees start exploding randomly when destroyed (e.g. via gun or by running over with a tank).
easily reproducible by running base mod + ir2 + dectorio, starting a new game, walking up to a tree and 'c'-attacking it with your shotgun, if you destroy it, the explosion animation plays on the destroyed tree :P
(this doesnt happen with only ir or only dectorio installed, so probably a compatibility problem)

oh, and factorio version 1.1.27, ir2 2.1.4 and dectorio 0.12.2

**Comment by Deadlock989** [comment]
That's hilarious.

Turns out to be because Dectorio adds a crafting recipe for trees. IR2 reworks all death explosion effects for any entity that has a recipe and uses the right particle animations based on what materials went into the crafting - you can see tiny wood plank particles flying off the trees if you ignore the Michael Bay fireball. It never occurred to me that someone might give trees a crafting recipe.

**Comment by Kevin-T4E** [comment]
Probably not worth the effort, but keeping the particle effects and removing the fireball would make for some satisfying destruction.

**Comment by Deadlock989** [comment]
This is fixed for the next version but there is not enough in it to warrant a release. I will upload it in a couple of weeks if no-one else reports anything substantial by then.

**Comment by Deadlock989** [comment]
I attempted to upload this and another fix today but received a mod portal error. I will try again if the devs or anyone else can help solve the upload issue.

https://forums.factorio.com/viewtopic.php?f=189&t=97757

**Comment by Deadlock989** [comment]
This fix is now uploaded to the portal. Turns out the portal was running out of disk space.
