### ISSUE TITLE
Slow firing rate of the atomic artillery shell from an artillery wagon

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#370]
In the Editor Extensions (`/cheat all`), artillery shell firing rate bonus is +100% according to the bonuses UI. The firing rate of the artillery train is one per 120 seconds for the atomic artillery shells; the normal artillery shells fire rapidly. I tested this by creating four worms, each isolated from the blast wave and timed the deltas between firings.

Is this intended behavior? I can understand there being a delay to allow the munition to travel, explode, another delay for the blast wave before re-acquiring and firing again as to not "waste" the expensive shells. However, 120s at +100% feels excessive during play. My use-case is I want to send the artillery train to a depot, wipe out everything in range, and come back. For this to happen, the train has to remain at the depot for a *long* time. In my current game, I thought the cannons were initially broken.

I didn't test it with a ground-based cannon.

**Factorio version, IR version**
1.1.101, 3.1.16

**Other mods installed**
Only IR mods and Editor Extensions

**Comment by Deadlock989** [comment]
Most of this is intended although it is not intended that artillery shooting speed has no effect on atomic artillery shells, which is what seems to be happening here. Atomic artillery shells have a 120 second reload time, and reload time is triggered when a magazine runs out - but artillery shells effectively have a magazine size of 1 so this means that artillery guns have to wait 120 seconds every time an atomic shell is fired (regular artillery shells have zero reload). Reload time is not the same thing as firing rate, which is the gap between individual shots regardless of whether the magazine has finished or not, and it seems that reload time is not affected by the research, which is something I wasn't previously aware of. Factorio also does not give reload time in ammo tooltips, unhelpfully.

There does need to be a very significant gap between atomic artillery shots, although two minutes is probably overdoing it. They are expensive to make, they one-shot almost everything, and they produce ungodly amounts of pollution, so the idea was that the firing rate must not be any faster than the travel time for the longest possible shot, to avoid wasting a nuke on something that is about to die anyway, and to try and cap the amount of insane pollution and its consequences on other nests.

Unfortunately reload time is a property of ammo, but firing rate is a property of the gun. This means it is difficult, probably impossible, to have firing rate research affect both artillery shell types in the same way unless you allow nukes to be fired at exactly the same rate as regular artillery.

I will look at this again in the New Year; off the top of my head the only way to make this clearer is to remove the listed bonus from atomic artillery shells, and look at reducing the reload to something less conservative.

**Comment by Deadlock989** [comment]
Changes for the next version:

- Atomic artillery shells were given a new ammo category, which prevents them from appearing in the artillery shooting speed bonus list and from being affected by the research (the effect was negligible anyway due to the constant additional reload time). The internal "artillery wagon gun", used by both the wagon and the stationary turret, was updated to use this category as well as the vanilla category.
- Artillery range technology continues to affect atomic shells because artillery range bonuses affect the gun, not the ammo.
- Timed via script the flight of an atomic artillery shell, fired manually (2.5x the max range of automatic firing). With artillery shell range level 5 research completed, it took about 22 seconds to fly the maximum distance. With level 10 (a million science packs), it took 37 seconds.
- The atomic artillery shell's reload time was reduced from 120s to 30s. The shell's tooltip description now mentions this additional reload time.
