### ISSUE TITLE
Add stone to deep space mining

### ISSUE THREAD

**Issue by AlpacaStorm** [Deadlock989/IndustrialRevolution#388]
Since all other rescorce is infinite(oil), or can be mined by deep space mining, with the only exception being stone.

**Comment by Deadlock989** [comment]
Can you give me some context for this - are you in a post-rocket situation where you're struggling for gravel/silica? In a way, those two stone byproducts are "infinite" with DSM because they are produced (in low quantities) by ore washing. However I didn't ever run the numbers on whether that would be sufficient, but I'm guessing almost certainly not. 

It would feel weird to drag stone down from space when you're sitting on a huge surface made almost entirely of it. I would rather have infinite yield stone quarries instead.

**Comment by AlpacaStorm** [comment]
I didn't actually played that far.
I'm just theorycrafting if it is possible sustain a science factory only by DSM, and what is the maximun SPM of it, so I use factory planner mod to do the calculation. 
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/44841996/ccd8a68b-ec54-4636-96cd-c6979f12946d)
The result is this. Most ore are close to the ratio of DSM. And energy generation is not included.

I agree that use infinite yield stone quarries instead is a good idea. But what tech level would it be?
If it unlock too early/cheap, it would make stone ore on the ground feel worth less.

**Comment by Deadlock989** [comment]
Using Factory Planner for this is going to include some subjective decisions because there are several different routes you can take. I don't know how well FP can simulate a circuit-controlled dynamic hot/cold ore washing plant to fit the actual demand for secondary metals, either. However if I take all of your metal ore values there at face value, I reckon about 0.8k silica can be produced by washing it, while the listed amount of stone would convert to 12.4k silica (however some of this stone actually represents gravel, e.g. in concrete). So it's clearly nowhere near enough, whether or not the FP algorithm is already taking ore washing stone byproducts into account.

The first draft of DSM did include a sixth ore which was going to be a form of carbonaceous chondrite, apparently common in asteroids/comets, which would have produced some form of carbon but mostly gravel. However I abandoned it because it just led to yet another ratio balancing problem and the mod has more than enough of those.

I'm going to close this suggestion for now but I've put it on my to-do list to investigate some way of obtaining "infinite" stone, either via DSM or some other route. I'm not sure how soon I will be able to get to it.
