### ISSUE TITLE
Sour Gas - Containers

### ISSUE THREAD

**Issue by RepairmanSki** [Deadlock989/IndustrialRevolution#389]
**Describe the issue**
Sour gas cannot be placed into any container for non-piped transport. Found when attempting to use logistic bots to transport small volumes for poison capsules. Obviously the other materials can be transported to the gas but that's not quite the point.

**Factorio version, IR version**
Factorio - 1.1.104
IR - 3.1.20

**Other mods installed**
N/A

**Comment by Deadlock989** [comment]
Sour gas is not the only gas with no item transport. Polluted steam, fossil gas, compressed air, and ammonia also have no item transport container. Polluted steam isn't required to craft any other solid item. Compressed air can be made anywhere out of "nothing" so it doesn't need a container. Fossil gas and sour gas are mixtures of several things. 

I don't really have a solution for this, at least, no solution that I like. The problem is that sour gas represents a vague mix of nasty things (hydrogen sulphide, sulphur dioxide, carbon monoxide, carbon dioxide, and water/steam) that you get from a whole bunch of different petrochemical processes in differing amounts. It's deliberately vague on exactly what is in there for simplicity/gameplay reasons. The first three of those gases do not exist separately in the mod and I don't want to change that.

Apart from steam, gases can only be put in high pressure canisters if they are pure compounds, because if it is a gas mixture (like air or fossil gas or sour gas) then the cryogenic process separates it instead of compressing it. There is an exception made for high octane fuel but really that should be in a different kind of canister (the copper and iron canisters for steam/petroleum did not exist back when I turned vanilla's "rocket fuel" into a fluid). Again, I don't want to change this because it would break a lot of games, even though the high octane fuel thing bugs me.

The only one of those missing gases that's reasonable and easy to add is ammonia because it is a pure compound, and liquified ammonia does exist in real life industry. My Blender scripts even spat out icons for liquid ammonia and the canister version, so third party add-on mods could add it easily if they like. But to me there didn't seem any point in cluttering the menus and RAM with it when ammonia's only current use is to make fertiliser with, which you are better off doing a metre away from the ammonia plant.
