### ISSUE TITLE
2.0 planning ahead

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#390]
Are you planning to support some version of IR for the 2.0 version? I assume not the Expansion as that is an overhaul in and of itself, but I heard multiple pipe filters are coming along in 2.0 vanilla… finally generic iron gas pipes and chromed Liquid Metal pipes or whatever the heck you want to do with those. How much will 2.0 break and how worth it will it be to fix? Love the mod! Thanks

**Comment by Deadlock989** [comment]
Short answer - I don't really know, it depends on a lot, but I expect IR3 is more likely to get some sort of update than not.

Long answer - in the following I'm using 2.0 to mean the Space Age paid-for DLC expansion mod and 1.2 to mean the updated base version of Factorio that will be released to everyone .

- IR3 will not be compatible with the 2.0 DLC.
- What happens with 1.2 depends on how much of the API is changed/broken and exactly what new tools and toys become available. The test for whether or not I'll be motivated to update IR3 is something like (coolness of new features * leisure time available) > (hassle introduced by breaking changes).
- I have a fairly large but only half-built IR3 add-on on the go, but progress on it has slowed considerably. Mostly because I have a new job and less free time, but also because the needed graphics are taking longer than I thought and I'm also having difficulties integrating the new ideas into the existing IR3 tech tree. I'm also demotivated by the looming impact of the unknown 1.2 changes, I don't want to struggle with it only to have it all wrecked in six months' time. If I do want to continue with Factorio modding after 1.2 then I might use the add-on as the foundation of a completely new mod instead, either something in the spirit of IR4 or something a bit different, maybe even a mod that isn't compatible with the Factorio base mod. Or I might start modding Captain of Industry instead or learn to play the piano. It's too early to make firm plans.

**Comment by Cadams111** [comment]
Cool. Good luck with whatever you choose to do!
