### ISSUE TITLE
Balance: scattergun vs autogun ammo clip size

### ISSUE THREAD

**Issue by target-san** [Deadlock989/IndustrialRevolution#391]
**Describe the issue**

Autogun ammo seems under-balanced compared to shotgun one. Shotgun clip is 10 shots, each 12 x D (16 for steel) damage while autogun clip of the same tier is 10 shots too, D damage each. I understand that these two types of turrets serve different purposes and autoguns aren't necessarily full replacement of scatterguns (approx. same DPS due to firing speeds), they're roughly 10 times less effective in terms of resource usage. Maybe it's worth increase autogun clip size to 20? Or am I missing something?

**Factorio version, IR version**

Factorio 1.1.101
IR3 3.1.20

**Other mods installed**

Only small QoL's and IR3 addons

**Comment by Deadlock989** [comment]
The two ammo types have essentially the same scheme as vanilla, the only difference being that magazine clips in IR3 fire a physical projectile with a travel time (in vanilla magazine bullets invisibly teleport to the target and hit instantly). The IR series' ammo balance has barely changed since 2019; it is very late in the mod's life to start tinkering with it now.

Your DPS comparison is of maximum possible DPS, i.e. assuming that the projectiles are always going to hit. Cartridge ammo does fire multiple projectiles but they are inaccurate and will spread out with distance, so against a single target it becomes increasingly likely with range that some or most of them will miss, and at maximum range (which is less than magazine ammo) it is even possible for them all to miss. They also have lower damage per projectile than the equivalent tier of magazine ammo, so they are inferior in terms of overcoming damage resistance (more of a magazine bullet's damage will get past a more evolved enemies' resistances). 

Scatterguns/shotguns are therefore only superior against multiple swarming less evolved targets at close range, while autoguns/submachine guns can more consistently apply more damage to single incoming enemy for longer / over increased distance.
