### ISSUE TITLE
No iron patches generated.

### ISSUE THREAD

**Issue by David00** [Deadlock989/IndustrialRevolution#394]
Hello, I recently started my first IR3 game. No other mods are installed, besides what IR3 installs with it.

Here are the details of the map and mods:

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/17997328/9f00602b-2dd6-4d1e-a8d9-05401728afa1)

As you can see, I"m about 6.5 hours in and am to the point where I need iron. I've looked around and uncovered a bunch of the hidden black map area, and I cannot find any iron patches.

The map string is:

```
>>>eNpjZGBkyGAAgwZ7EOZhSc5PzIHxQJgrOb+gILVIN78oFVmYM7mo
NCVVNz8TVXFqXmpupW5SYjGKYo70/JwUdBO4M4t00zKLi0uLUouRxfm
B4kWlSUlAO0uKUlHlODKL8vPQDWItLsnPQxFhL8nEVIVhGHdpUWJeZm
kuukoGxpUuH3wbWuQYQPh/PYPC//8gDGQ9AAYUCDMwNkBUAsVggDU5J
zMtjYFBwRGInUDSjIyM1SLr3B9WTbFnhKjRc4AyPkBFDiTBRDxhDD8H
nFIqMIYJkjnGYPAZiQGxtARoBVQVhwOCAZFsAUkyMva+3brg+7ELdox
/Vn685JuUYM9o6Cry7oPROjugJDvIn0xwYtZMENgJ8woDzMwH9lCpm/
aMZ8+AwBt7RlaQDhEQ4WABJA54MzMwCvABWQt6gISCDAPMaXYwY0QcG
NPA4BvMJ49hjMv26P4ABoQNyHA5EHECRIAthLuMEcJ06HdgdJCHyUoi
lAD1GzEguyEF4cOTMGsPI9mP5hDMiED2B5qIigOWaOACWZgCJ14ww10
DDM8L7DCew3wHRmYQA6TqC1AMwgPJwIyC0AIO4OBmZkCAD/YMCxzXTg
MA1CK7Pg==<<<
```

Here's the area that I've uncovered:

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/17997328/80af9896-a032-416b-95c2-8f8e956eef84)

What would you recommend I do?

**Comment by Deadlock989** [comment]
You've simply been slightly unlucky, possibly due to the RNG of ore patches being obliterated by the placement of water. You've explored a decent area but I wouldn't say it was especially large (YMMV). If you import your map string into a new game's Map Generator and open the preview, you'll see that there are is a very large iron patch only about 1-2 chunks beyond your currently explored area, and several more about 3-5 chunks away in other directions. In total I'm guessing you have access to several million iron ore within the map preview area.

**Comment by David00** [comment]
Thanks for the quick response, @Deadlock989! I was wondering how I could preview the rest of the map and the built-in previewer totally slipped my mind. I will check that out and head that way shortly. I'm really enjoying IR3 so far! :)
