### ISSUE TITLE
Productivity modules in molten steel production in arc furnace

### ISSUE THREAD

**Issue by FrancoisDevemy5** [Deadlock989/IndustrialRevolution#396]
Hello,

Any particular reason why productivity modules are not supported in molten steel production?
They are allowed for steel ingot production in an electric alloy furnace.
As it is, it decreases the 50% productivity advantage of the arc furnace compared to the electric furnaces to just 25%.
This is also true for bronze and brass, but far less important.

Supporting productivity modules for steel would unlock the true potential of the arc furnaces, plus making the balance between iron and steel production even, for easier direct insertion.
With lots of beacons, productivity modules for iron and speed module for steel, it is slightly unbalanced. We need 6.4% more _iron_ arc furnace with 8 beacons per furnace, or 4.4% more _steel_ arc furnace with 16 beacons per furnace.

**Factorio version, IR version**
Factorio 1.1.104
IR 3.1.20

**Comment by Deadlock989** [comment]
Arc furnace recipes only allow productivity module bonuses if they are based on raw mineral input. Arc-melting recipes from ingots or molten metals do not allow productivity because that would be "double dipping". All of the iron sources in the arc furnace steel recipes have had a chance to benefit from productivity once already. I'm not planning on making any changes to these recipes at this late stage of the mod's life.
