### ISSUE TITLE
[Airships] Airship station lose their configuration when copied, cut or blueprinted

### ISSUE THREAD

**Issue by FrancoisDevemy5** [Deadlock989/IndustrialRevolution#399]
One paint point I have using Airship stations is that their configuration is easily lost.
Copy-pasting, cut-pasting, Delete-Undoing and blueprinting all lose the configuration of the new station (name, colour and other general setting, loading, unloading and forward instructions).

Is it possible to make this configuration persistent?

**Factorio version, IR version**
Factorio 1.1.104
IR 3.1.20
IR Airship 1.0.0

**Comment by Deadlock989** [comment]
The current API for blueprinting (which also covers copy-paste) is unreliable in several circumstances and, like some other Factorio modders, I have given up trying to work with it. Apparently there are improvements in this area for Factorio 2.0 but that may still be many months away. With regards to the undo queue, there is no API at all for it at all and I don't know if Wube plan on exposing it to the API.  

I did take the time to implement settings copy-paste between existing stations (shift+right-click to copy from source, shift+left-click to paste to destinaation) so that is the only workaround at present. I may (or may not) revisit this at some point after 2.0.

**Comment by FrancoisDevemy5** [comment]
I was not aware that Shift-clicking worked.
Thanks!
