### ISSUE TITLE
Include enough items in the stone-era starter pack for zero hand-crafting

### ISSUE THREAD

**Issue by rlundy** [Deadlock989/IndustrialRevolution#401]
Now that IR3 seems to be mostly in a settled state, I wonder whether you'd consider revisiting the idea of a zero-hand-crafting starter pack, similar to what IR2 had.

To accomplish zero hand-crafting, I think these basic items would be required at a minimum:

- Power generation: either 1 steam derrick, or 1 copper boiler plus 1 copper offshore pump
- 1 steam assembler
- 1 burner mining drill
- 1 stone furnace

I did some quick testing, and found:

**Stone** era: No steam assembler and no power generation.

**Copper** era: Many assemblers and small assemblers, but still no power generation.

**Bronze** era: Includes both forms of power generation, so currently only when starting in this era is zero hand-crafting possible.

It would only take a few additional items to make zero hand-crafting possible in stone and copper:

Stone:

- 1 steam assembler
- 1 steam derrick; or 1 copper boiler and 1 copper offshore pump

Copper:

- 1 steam derrick; or 1 copper boiler and 1 copper offshore pump

Would this be a possibility?

**Comment by Deadlock989** [comment]
Ref: #112 - basically my feelings about this haven't changed since then.

It wouldn't be any real work for me to add a steam derrick to the "copper age" starter kit and I have no objection to doing that in principle. (But I don't want to add anything to the "stone age" kit.) However, the Lazy Bastard achievement is currently disabled. If I re-enable it, I'll be back to square one where people are complaining that Lazy Bastard is impossible on default settings. The proper way to "fix" Lazy Bastard is the same as before - someone needs to be work out the minimum number of handcrafts needed to bootstrap a large assembler with the default starter kit, and then the Lazy Bastard achievement can be updated properly so that it always works. But that someone is not me. 

If you're not talking about Lazy Bastard and just want a self-set challenge where zero handcrafting is possible, then I'm happy to add a steam derrick to the "copper" setting (it would most likely end up in all the non-default settings).

**Comment by Deadlock989** [comment]
The "copper" starting tech setting will include a steam derrick in the next version, but I don't currently have a timescale for release.

**Comment by rlundy** [comment]
I don't guess I care a lot about the achievement...though it was with IR2 that I first got it; I've never had the patience to do it on vanilla.

I enjoy a play style of handcrafting nothing, if possible.  In IR2 with the starter kit I could do that, but in IR3 it's unfortunately not possible.  That's really what I'm looking for.  I guess another option would be a small add-on mod that would modify the starting items to include the things I've identified above, but I don't know much about Factorio modding and don't have a lot of spare time to learn.

Well, OK, to be fair, if I have the time to _play_ Factorio, how can I say I don't have the time to learn to _mod_ Factorio?  😁
