### ISSUE TITLE
Minor graphical inconsistency related to X pipe junctions

### ISSUE THREAD

**Issue by Dev-iL** [Deadlock989/IndustrialRevolution#405]
Please consider the following two screenshots, which contain a copper steam pipe "T" connection which becomes "X" when rotating a machine with a fluid connection. The X connection is a bit shifted to the north (note the small step in the pipe connections right and left).

![T connection](https://github.com/Deadlock989/IndustrialRevolution/assets/6509619/6e4f70f0-61d0-45ec-9422-dfc8b0a63e8a) ![X connection](https://github.com/Deadlock989/IndustrialRevolution/assets/6509619/b6c8bf69-77e6-4142-af40-8a05003e33ba)

I'm on the latest stable Factorio and IR3 as of today.

**Comment by Deadlock989** [comment]
Literally unplayable.

This wasn't only affecting the X-junction version of the pipe sprites but some others as well, notably the T-junctions. All of the pipe sprite variants that intrude out of the tile to the south had to have that part clipped out in the sprite definition back when the Loaders & Stacking mod was introduced, due to it being the only way I could find to solve some nasty render layer order problems. Because the sprite is shortened in height, it has to be shifted northwards slightly to compensate. But the maths had a typo (dividing the height difference by 120 instead of 128) resulting in the sprite being shifted 0.9333 pixels too far north.

Fixed for next version.
