### ISSUE TITLE
Wooden crate is stronger than early metal chests

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#408]
Wooden crate has more health than tin and bronze chests. Because of this, a wooden crate is better than a tin chest, which has the same storage, and partially better than a bronze chest. The case of the tin chest looks especially strange given the fact that a tin pallet has the same health as a wooden pallet and has more storage. It seems to me that metal chests should have more health than crates made from easily accessible wood.

And I think that tin and bronze chests should have some kind of resistance like iron and steel chests.

**Comment by Deadlock989** [comment]
It looks like all vanilla chests were missed from the standardised resistances and hit points pass.

I'll address this in a future release. Note that tin storage containers only exist in the mod at all because of a request from a player that liked to start in desert scenarios with very little wood - they are intended to be absolutely equivalent to wood. At most the tin storage will get the copper tier resistance (75% fire, 25% impact) but it will not have more health than wood. Tin is extremely soft and a good timber wood is far stronger.

**Comment by Deadlock989** [comment]
- Wood pallet health remains at 50
- Tin pallet health remains at 50
- Wood crate health reduced from 100 to 75
- Tin chest health increased from 50 to 75
- Bronze chest health increased from 75 to 150
- Iron chest health increased from 200 to 225
- Steel chest health reduced from 350 to 250

- Wood pallet and crate gain standard tier resistances (impact 25%)
- Tin pallet and chest gain standard tier resistances (fire 75%, impact 25%)
- Bronze chest gains standard tier resistances (fire 75%, acid 50%, impact 35%)
- Iron chest resistances increased to standard tier (fire 75%, impact 50%, explosion 50%/-3, physical 50%/-3)
- Steel chest resistances increased to standard tier (fire 75%, acid 50%, impact 65%, explosion 75%/-10, physical 50%/-3)

**Comment by Deadlock989** [comment]
Also adjusted logistics chests to follow the steel chest scheme.
