### ISSUE TITLE
[Loaders & Stacking] Electric loaders consume energy inconsistently

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#412]
**Describe the issue**
Electric loaders consume energy from the electrical network inconsistently; their consumption graph resembles a saw. The peak of this saw reaches 256 kW for all three loaders despite different average consumption. They do not appear to have an electrical input limit. This is not a big problem, but I think it would be better if the loaders had an input limit for a more even energy consumption.

**Factorio version, IR version**
Factorio 1.1.104, IR 3.1.21, PL&IS 1.0.10

**Comment by Deadlock989** [comment]
Electric loaders are weird in that they consume a specified amount of energy per item loaded. There's nothing else quite like them in the game. So I don't know if setting an input limit would actually help, but I will take a look.

**Comment by Deadlock989** [comment]
It turns out that if you set the loader's input flow limit to the same as the maximum energy consumption (as determined by the speed of the corresponding belt multiplied by the energy consumed per item), and give them a fixed size energy buffer that can hold it, it fixes the "Electric network info" graph issue, but there is a new side effect: a weird rapid flickering of the energy consumption bar in the entity tooltip (yellow/green as it loses energy then regains it next tick). If you give it enough of a "bonus" limit to make that go away, then saw-ing on the graph returns. I don't think this is fixable at my end and I don't like the weird energy bar flicker so I'm leaving this as it is. This can only be fixed properly by the Factorio devs (but I don't fancy your chances given that electric loaders are not a vanilla feature).
