### ISSUE TITLE
interaction with Space Extension (not Space Exploration)

### ISSUE THREAD

**Issue by shoobedoo926** [Deadlock989/IndustrialRevolution#417]
Space Extension adds a series of lategame researches, the first of which costs only several hundred thousand red science, the second several hundred thousand red and green, &c. You'd expect this to hold when installing IR3, but this set of researches all cost all 5 non-military basic sciences on my save (except for the last one, which also costs all 6 non-military science both with and without IR3). I suspect this is some kind of override in IR3 specifically, because other overhauls that change/add science packs (Bob's mods, K2) _do_ correctly cost these researches.

Playing on Factorio 1.1.107, first noticed the issue on 1.1.104 (though it may have been present before). Running IR 3.1.22.

The issue persists in a save with _only_ IR3 and Space Extension installed.

**Comment by Deadlock989** [comment]
I'm not familiar with SX. IR3 does enforce science pack dependencies and there are rare cases where this doesn't work out well with third party mods. For any combo of complex overall/interaction mods, it is likely that some custom tweaking will need to be done by one mod author or another to get them to play together optimally, because every mod is fighting for slices of the same prototype pie. However, SX is not a mod I'm personally interested in supporting myself. 

There is an fork of SX with specific support for IR3, I don't know if that is the one you are using, or whether or not it addresses this issue: https://mods.factorio.com/mod/SpaceModFeorasFork
