### ISSUE TITLE
[Feature request] Mirrored version of Advanced Forestry

### ISSUE THREAD

**Issue by pumbatrade** [Deadlock989/IndustrialRevolution#421]
Hi just a small aesthetic request. 

Would it be possible to add a mirrored version of the Advanced Forestry where the Ammonia and CO2 inputs are swapped? This would be similar to the mirrored Air Separation recipe of the cryogenic plant. 

This could improve the look of the pipe mess of Forestry areas where it is very common to place 4 forestries together at the edge of 4 bordering chunks.

**Comment by Deadlock989** [comment]
Unfortunately it's not really possible, or at least very difficult and probably clunky, because forestries don't provide any way of selecting a recipe - it is automatically updated when trees and forestries within range appear and disappear. Currently it would probably require a completely separate "mirrored building".

I think I saw somewhere that Factorio 1.2 is going to provide base game support for mirrored recipes, so this might be something to explore if IR3 is updated for that. I'm also not a big fan of the "corner layout", I completely get why it's done and I've done it myself in playthroughs but it seems like a weird consequence of the single chunk forestry mechanism, so I would prefer to rethink that entirely (e.g. find a performant way of having forestries use a proper radius instead of being chunk-based, or perhaps expand them to cover 3x3 chunks).
