### ISSUE TITLE
No access to researched text plates when text plates is installed mid-playthrough

### ISSUE THREAD

**Issue by geekofalltrades** [Deadlock989/IndustrialRevolution#424]
**Describe the issue**
I installed [Text Plates](https://mods.factorio.com/mod/textplates) in the middle my IR3 playthrough. The only plate recipes available to me are the copper and stone plates that are available from the start of the game. Even though I have Iron, Steel, Glass, Gold, and Concrete 1 researched, the corresponding plates are not available for me to craft.

Also, not sure if this is intentional, but the Plastics tech doesn't unlock the plastic text plates.

**Factorio version, IR version**
* Factorio: 1.1.107.66234 (win64)
* IR3: 3.1.23
* Text Plates: 0.6.10

**Other mods installed**
`jq '.mods | map(select(.enabled == true).name)'`
```json
[
  "base",
  "alien-biomes",
  "alien-biomes-hr-terrain",
  "AutoDeconstruct",
  "automatic-station-painter",
  "Automatic_Train_Painter",
  "bullet-trails",
  "DeadlockBlackRubberBelts",
  "DeadlockLargerLamp",
  "EditorExtensions",
  "even-distribution",
  "extended-descriptions",
  "flib",
  "IndustrialRevolution3",
  "IndustrialRevolution3Assets1",
  "IndustrialRevolution3Assets2",
  "IndustrialRevolution3Assets3",
  "IndustrialRevolution3Assets4",
  "mining-patch-planner",
  "ModuleInserter",
  "pump",
  "Quicksave",
  "RecipeBook",
  "RemoteConfiguration",
  "textplates",
  "Todo-List",
  "TrainGroups",
  "VehicleSnap",
  "WireShortcuts"
]
```

**Comment by Deadlock989** [comment]
I guess this is IR3's issue because it changes the tech requirements for the plates. The unlocks are refreshed automatically if IR3 is also updated, but not if only Text Plates is added or updated. To be fixed in a future release.

If you don't care about cheevments you can force a tech unlock refresh in a single player game by running the following console command:

```/c game.player.force.reset_technology_effects()```

Regarding the plastic plates - they seem to be new(er). Previously they only existed in the Even More Text Plates add-on (which was a fork of one of my mods originally). I'll look at this when I address the tech unlock issues.

**Comment by Deadlock989** [comment]
This is fixed for the next version, next week or so.
