### ISSUE TITLE
Separate graphics mod?

### ISSUE THREAD

**Issue by dgattey** [Deadlock989/IndustrialRevolution#43]
First of all, thanks for making an absolute blast of a mod to play. I'm at like 120 hours on my latest map with IR2 and it's my favorite play through yet. It's gorgeous, quirky, and so well balanced.

Any chance you could move just the graphics to a separate (required) mod like Space Exploration does? That way bug fix updates like today's don't have to download allllll the graphics again even if nothing changes outside some code. Despite fast-ish internet, IR2 is consistently > 2-3 min to update because of all the images. Not a real problem, but would improve the experience a bit! Thanks.

**Comment by Deadlock989** [comment]
Thanks for the compliments, it's appreciated.

I have considered doing this - I live in the UK where we have highly asymmetric broadband and uploads are very painful. 

However, it comes with an overhead of actually doing the work to separate the graphics out. Then there is an ongoing overhead of having to update and upload two separate mods every time any graphic changes, even if it's a single icon. I'm fairly sure that today's was only the second or third out of thirteen releases of IR2 that didn't touch any of the graphics. So if I had had them as separate mods from the start, releasing updates would have been more work for me overall but very little discernible benefit to players.

So the question becomes one of deciding when the best time to do it is - and a possible answer is still "never" because I don't think there are going to be many more updates to the mod anyway.

**Comment by dgattey** [comment]
Fair enough, sad that there won't be more cool content added, but that all makes sense. Thanks!

**Comment by Deadlock989** [comment]
Re-opening as the time feels right to finally action this.

To do:

- Split media (icons, sprites, sound) into 3 or 4 separate mods of approx 30-40Mb each
- Update all manual references to media
- The `DIR.get_layers()` call frequently used to quickly make standardised animation sheets will need a bit of finessing to get the sprite path right - most likely some kind of look-up table
