### ISSUE TITLE
Inspirations issue with locked technologies (MSI-2 compatibility)

### ISSUE THREAD

**Issue by Lesbian-Catgirl** [Deadlock989/IndustrialRevolution#433]
The issue
Tested the gameplay with Inspiration and MSI 2 (https://mods.factorio.com/mod/Mining-Space-Industries-II) and there are some problems: MSI makes "locks" some technologies, so player can see it, but can't research until it is unlocked by doing MSI quest. The problem is, when locked tech is also researches by inspiration, it becomes broken after unlocking.

For example, Green science is locked and researched by creating 12 iron ingots. Those ingots also unlock previous "Iron-working" tech (which must be done, or quest for green science will not spawn, thats how MSI works). After comleting quest it unlocks science tech, but it is not researches by iteself (which is mostly expected), and is also don't research after creating, taking, smelting new iron ingots.
Also, for some reason, after unlocking you can select this tech as research goal and it doesn't show the message that it can't do it due to Inspiration. The same problem occures with Blue Steel (Chemical) pack research.
"Crude oil processing" is also locked by quest, but it researches if you complete inspiration goal and get 120 oil (which skips the quest, feels wrong and also incorrect, after solid material locked techs did not completes after inspirations goal while being locked).
Purple pack do not need any material, but it also do not ulock after quest (and of course previous technology).
Covarex, for some reason, behaves like oil - skips quest, when 12 U-235 are obtained.

The most expectext thing is that locked techs can't be researched by any means, until unlocked, and the either automatically researches, if all conditions were already met, or starts checking condition from the moment it unlocks.

If there is nothing you can or want to do with this issue, maybe you can tell, how to modify another mod, so those interactions will work as expected. Thank you.

Versions
IR3 v3.1.26
IR3: Inspiration v1.0.2
MSI-2 v0.8.5

Other mods installed
MSI 2 with only with necessary dependencies, IR3 with all official addons including Inspiration, Editor Extensions

**Comment by Deadlock989** [comment]
Thanks for the report. This sounds complicated. I'm not familiar with MSI2 and I'm surprised that it works with IR3 at all, but it seems the author has made some efforts to make it compatible. I have a really busy week ahead so it will be a while before I can take a look at this, but I will when I can. But my gut feeling is that Inspiration and MSI2 are trying to do the same kind of thing and it will be difficult, or not possible, to resolve.

**Comment by Deadlock989** [comment]
I took a quick look at this. There are a number of issues but the main one is that MSI2's "mission" mechanic is working at cross purposes to IR3:Inspiration. They are both trying to conditionally enable and disable technologies with different triggers under different conditions, and they make different assumptions about what should be made available and when. A particular problem is that MSI2 moves analysis packs out of their IR3 milestone techs back into the re-enabled vanilla science pack techs, which IR3 does not use, so when MSI2 is installed, the triggers set up by Inspiration make no sense. It would take dedicated scripting to resolve these conflicts, either within IR3:Inspiration or MSI2. This is not something I am personally interested in doing.

For now, in order to avoid wasting people's time, I will mark the next version of IR3:Inspiration as incompatible with MSI2. If the situation changes in future then I can remove the flag on request.
