### ISSUE TITLE
Main mod isn't detecting asset mods and asset mods isn't detecting main mod

### ISSUE THREAD

**Issue by yakan12** [Deadlock989/IndustrialRevolution#442]
I'm experiencing issues with the "Industrial Revolution 3" mod for Factorio. The mod requires 4 asset mods to function properly, but I'm encountering the following problems:

The first three asset mods are not being detected or working, despite having the correct versions installed.
The fourth asset mod is requesting a version (3.1.0) that does not exist.
These issues are preventing the mod from functioning correctly. Could you please investigate and provide guidance on how to resolve these compatibility issues? Thank you for your attention to this matter.

Factorio version: 1.1.107
Mod version: latest version avaible right now.

**Comment by Deadlock989** [comment]
The cause is almost certainly going to be that you have another incompatible mod installed, but you haven't listed your mods so I don't know which. Check the mods listed in red under "Incompatible with" on the main IR3 mod and if you have any of them active, they will have to be deactivated.

> The fourth asset mod is requesting a version (3.1.0) that does not exist.

No, it is requesting any version in the 3.1.x branch with a patch number equal or higher (>=) to 0, which includes the latest version (3.1.28).
