### ISSUE TITLE
Deconstructing machine doesn't spill the fluid in IO slot

### ISSUE THREAD

**Issue by lingluo3** [Deadlock989/IndustrialRevolution#444]
Issue:
I'm using a sandbox.
Put a stack of Liquid CO2 canister into an unbarreling machine, then wait for it to work. The unbarreling machine is powered but not connected to any pipe. After it stops, it should have 480 liquid CO2 in its output. Deconstruct it, and the 480 liquid CO2 is gone, not creating any spill.

Mods and versions:
Factorio v1.1.109   IR3 v3.1.27

Only IR3 with some addons, no other overhauls.
Addons: Linear inf mining prod, deep space mining, inspiration, loaders, production scrap.

**Comment by Deadlock989** [comment]
This is working as intended. To avoid having to add a scripting overhead to every single building deconstruction, pollution spilling is only applied to pipe and tank type entities, and the wording of the Manifesto page on pollution spills reflects this. Since there is no way to automate the deconstruction of buildings, I don't consider this to be an exploit worth the cost of fixing.

**Comment by Deadlock989** [comment]
I rethought this and revisited the code; the existing framework can be extended to include crafting machines without much additional overhead. This change will not appear until version 3.2.0.
