### ISSUE TITLE
Use of red cross  on health pack

### ISSUE THREAD

**Issue by joshuawsmith** [Deadlock989/IndustrialRevolution#446]
**Describe the issue**
It looks like the health pack icon uses a red cross on it.  That symbol is protected by different international laws and cannot be used in video games.  This comment provides a pretty good discussion on the issue.  https://www.reddit.com/r/gamedev/comments/5okv7q/video_games_arent_allowed_to_use_the_red_cross/?rdt=56987

**Factorio version, IR version**
Factorio: 1.1.109
IR3 version 3.1.20

**Comment by joshuawsmith** [comment]
Sure.  https://www.redcross.org.uk/about-us/what-we-do/protecting-people-in-armed-conflict/the-emblem

Provides the general info for the UK.

“ Unauthorised use of the emblems is forbidden in international and national law. The British Red Cross monitors unauthorised use or misuse (deliberate or accidental) of the emblems and similar designs in the UK.”

**Comment by joshuawsmith** [comment]
I can also dig up some news stories of other developers getting cease and desist letters if you’d like

**Comment by joshuawsmith** [comment]
The pdf linked on the red cross site does provide some alternatives, on of which is just flipping the colors.  White cross on a field of red

**Comment by Deadlock989** [comment]
> I can also dig up some news stories of other developers getting cease and desist letters if you’d like

Presumably they would have to serve such a letter to Wube. I'm not a game developer. This is a mod for someone else's game. The mod is free for non-commercial use. I'm not a company.

It does make you wonder what kind of caring, humanitarian organisation would threaten a hobbyist with legal action because his free game mod contains a couple of pixels that look like a red cross. Still, I imagine the impact this Factorio mod has on world conflict is immense. I'll look into changing it to something completely different - perhaps a white cross on a red background - the moment I can be arsed.

**Comment by Deadlock989** [comment]
The icon will be replaced with the following in the next release of the mod. There is no planned date for this however, as there are no other updates or fixes pending, and I'm disinclined to force everyone to update the graphics pack for this alone.

![medical-pack](https://github.com/user-attachments/assets/c23a1a88-a665-4bde-b18e-c32e184db1e0)
