### ISSUE TITLE
Converted prereqs added more than once (was: Jetpack mod support)

### ISSUE THREAD

**Issue by Mohkhasa** [Deadlock989/IndustrialRevolution#45]
Hello,

I get an error if I add Jetpack mod, is it possible to fix this issue?
![](https://i.imgur.com/1WPyZSv.png)
`  10.876 Checksum of IndustrialRevolutionStacking: 2703272848`
`  11.130 Error ModManager.cpp:1574: Error while running setup for technology prototype "jetpack-4" (technology): Technology prerequisite "ir2-modules-3" is registered more than once.`

p.s. amazing graphics and ideas. one of the best mods in my opinion. great job

**Comment by Deadlock989** [comment]
Normally I wouldn't take requests for specific mod support but this looks at first glance like a more general issue with the bit of code that handles conversion of unused vanilla technology prerequisites. I will take a look when I get a chance.

**Comment by Deadlock989** [comment]
This issue is fixed for the next version but that's unlikely to be released very soon. You can patch it yourself in the meantime by changing line 57 in code/technology/technology-prereq-convert.lua from:

`tech.prerequisites = table.deepcopy(new)`

to

`tech.prerequisites = DIR.unique_values_only(new)`

**Comment by Mohkhasa** [comment]
Thanks alot, Its working now.
