### ISSUE TITLE
Steam Drill is beaconable

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#450]
**Describe the issue**
Manifesto says steam machines are not affected by beacons, however beacons do affect the steam drill.
![IMG_1844](https://github.com/user-attachments/assets/a1ba0f28-4672-416d-bc96-be8d54df1739)
Edit: also applies to Burner drill

**Factorio version, IR version**
Base 1.1.109
IR3 3.1.29

**Other mods installed**
IR3 suite, Factory Planner

**Comment by Deadlock989** [comment]
Good catch. This also affected steam derricks. Fixed for next version.

I had been assuming for the last five years that setting `allowed_effects` to `nil` prevents beacons from affecting an entity, but it turns out that is only true for crafting machine prototypes - for other entity types such as drills, it needs to be set to an empty array.
