### ISSUE TITLE
request to make an addon

### ISSUE THREAD

**Issue by the-clorax** [Deadlock989/IndustrialRevolution#55]
I am working on an addon that requires your mod to add compatibilities between this mod and other mods, but under your license i can not add modified versions of any of this mod's assets without your . Can i have your permission to add modified versions of your graphics to Industrial Revolution - Compatibility Fixes? Immersite rivets, stainless steel machine hulls, matter analysis packs, and so on will be added to the mod (when Kastorio 2 is present) and possibly similar materials for when other mods are present.

Thank you

**Comment by Genhis** [comment]
Out of interest, which mods are you making compatible with IR2?

**Comment by Deadlock989** [comment]
It sounds like you are going beyond simple compatibility/conflict patching and actually creating hybrid mod content. 

I'm going to say no because I've said no to other people in the past and also had stuff taken off the portal when the people concerned just ripped stuff off without even asking. It would set some weird precedent and I'm not into it.

In the past I created specific icons at Linver's request for Krastorio 1 (e.g. scrap, plates, rivets and ammo in tantalum or the pink crystal stuff - I have no idea if either of those materials are still a thing in K2). But for any purely metallic component you could just tint the IR2 carbon steel versions (which are almost greyscale, they have a tiny bit of blue in them) and it would look pretty much exactly the same as the tantalum icons in K1. You can do that without having to actually redistribute copies or derivatives of the sprite by simply referring to the sprite path in IR2, e.g. `__IndustrialRevolution__/graphics/icons/64/steel-gear-wheel.png`, and then using the `tint` property (hint: that kind of tinting works best with pale low saturation colours). 

There are some component variants that steel doesn't use, e.g. the 8-toothed gear, the plain rod, the ingot variants etc. I am happy to include a full set of pure greyscale component icons in IR2 that aren't used by the mod itself but are available to other mods to reference and tint. I can even provide a shiny version and a dull version. Let me know if that works for you.

I don't know what a "machine hull" is. The "analysis pack" icons are not my work - they are simply the vanilla science pack icons from 0.17, except they were based on the (at that time) 128x128 technology icons rather than the "new" science pack item icons that came in 1.0 or 1.1 or whenever. From memory those and the rubber tree icon are the only repurposed vanilla assets remaining in the mod.

**Comment by the-clorax** [comment]
i have never worked with tinting before, but i will gladly use the greyscale components if you let me. By machine hull i was talking about the large and small machine frames. Thanks.

**Comment by Deadlock989** [comment]
I ran off a series of greyscale metal versions of all the basic components and some of the metallic intermediates such as frames and pistons. They are all available in a dull metal and a shiny metal version. A subset (plates, ingots) also have an anisotropic version (brushed metal effect). These will be included for other mods to reference in the next version (later this month).

**Comment by the-clorax** [comment]
where can i find these graphics? they don't seem to be in the graphics folder of your mod.

**Comment by Deadlock989** [comment]
> These will be included for other mods to reference in the next version (later this month).

**Comment by the-clorax** [comment]
sounds good. 

> 
> 
> Out of interest, which mods are you making compatible with IR2?

i am hoping to further integrate kastorio with IR2 by adding things like immersite machine casings and changing the mining drill pollution from kastorio back to what it is in IR2

**Comment by Genhis** [comment]
Would it be possible to include greyscale beams? I am interested in metallic versions as well as wood-beam and copper-beam overlay in greyscale (I would combine wood-beam with copper-beam overlay in my preferred colour).

**Comment by Deadlock989** [comment]
OK, I added these for the next version.

![image](https://user-images.githubusercontent.com/3128845/125003003-18053f00-e04e-11eb-9041-93c67ec7de5e.png)

**Comment by Deadlock989** [comment]
@Genhis Are you still planning on using these or can I remove them?

**Comment by Genhis** [comment]
Yes, I am. The AAI Industry patch is mostly finished and in closed testing. Sorry that it takes so long, I had to prioritise other work.

Space Exploration patch is also work-in-progress but I don't think it's going to be done any time soon. Earendel had some interesting ideas how to combine the content together.
