### ISSUE TITLE
Ignore alternative recipes as prerequisites if they are deeper in the tech tree

### ISSUE THREAD

**Issue by Genhis** [Deadlock989/IndustrialRevolution#58]
On the topic of Space Exploration compatibility... Let's say that I have two low density structure (LDS) technologies. One is unlocked in blue science, the other in purple science. Purple science LDS is an alternative variant which is more cost-efficient. Currently, when any technology needs LDS recipe, both of them are marked as prerequisites. I want only the first (blue science) technology to be considered for prerequisites when tech tree is regenerated.

I have tried setting `IR_tech_rebuild_ignore = true` flag to the alternative recipe but this removes all prerequisites set by the alternative recipe to the alternative tech. I want this recipe to be ignored by all other technologies but not the ones which unlock it.

I see three possible solutions:
1) Ignore all recipes which are unlocked deeper in the tech tree / which require more science packs (e.g. this requires a purple one)
2) Make recipes with `IR_tech_rebuild_ignore = true` to be ignored only by other technologies, not the ones which unlock them
3) Add another flag for this?

Am I missing something?

**Comment by Deadlock989** [comment]
This is exactly the situation the flag was created for. The general problem is surprisingly complex. For example "deeper in the tree" would require that the earlier tech has to be a direct ancestor of the later one, which isn't necessarily going to be the case, so what do you do if it isn't; the cost of science packs is itself based on branch depth so it hasn't even been calculated yet, chicken and egg. I did spend some time trying to solve it algorithmically but gave up because there were too many quirky situations and it was less effort to work around the small number of exceptions. If I were going to rewrite it from scratch I'd approach it differently now but that's not going to happen.

The way IR handles this for techs in vanilla (e.g. kovarex enrichment) and IR (e.g. furnaces 3) is that they mark the tech with `IR_tech_rebuild_ignore = true` and set the prerequisites manually.

**Comment by Genhis** [comment]
I'd like to try the algorithmic approach and create a new flag.

What do you say to this? It seems to do what I want and I don't see any negative consequences.

    -- line 49 in technology-regenerate.lua
    if (not DIR.is_a_multi_recipe(effect.recipe)) and (not data.raw.recipe[effect.recipe].IR_tech_rebuild_ignore_provider) then

Recipes with `IR_tech_rebuild_ignore_provider = true` would not be considered as valid ingredient providers.

**Comment by Deadlock989** [comment]
OK, you've persuaded me, as it also helps with another niggle I've had for some time.

- Recipe property `IR_tech_rebuild_ignore_as_provider = true` will prevent a recipe being considered as a provider (it must still be in a vanilla tech or an `IR_native` tech to be considered at all, and the tech and the recipe must still not have `IR_tech_rebuild_ignore` set).
- Public function `DIR.is_an_ignored_ingredient_provider(recipe_name)` returns true if the named recipe exists and has the flag set.

IR now sets this flag itself on any system component that has multiple sources, except for the one marked as the main source in the component table. For example, iron ingots can be made from ore, gravel, pure, and scrap; ore is considered the "main source", which results in a recipe name of simply "iron-ingot", while all the other sources produce an "iron-ingot-from-X" recipe name and now also have the `IR_tech_rebuild_ignore_as_provider` flag set as well. Same also applies to things like plates ("lead-plate" is the main provider from ingots, "lead-plate-from-molten" is a non-provider). This allowed me to finally get rid of the hacky `DIR.is_a_multi_recipe()` function completely.

The techs listed in `DIR.ancestor_tech_ignore_list` and the recipe substrings listed in `DIR.ignored_recipe_substrings` are also now converted to the corresponding prototype flags at the start of the tree build, instead of having to be checked separately.

This will be available in IR 2.2.0 (later this month).
