### ISSUE TITLE
Fast replace group / load order shenanigans with unsupported mods

### ISSUE THREAD

**Issue by Czarniak4** [Deadlock989/IndustrialRevolution#71]
After the last update each time I try to load my game I'm getting the below error:
"Failed to load mods: Error while running setup for entity prototype "big-wooden-pole" (electric-pole): next_upgrade target (big-electric-pole) must have the same fast_replaceable_group (electric-pole != big-pole)."

I'm getting it even when it's the only mode I load.

**Comment by Deadlock989** [comment]
Nothing changed with big wooden poles in that release (or for many releases previously).

Can't reproduce when IR2 is the only mod loaded.

Please provide a full mod list or if it's easier a saved game.

**Comment by Czarniak4** [comment]
[IR 1.zip](https://github.com/Deadlock989/IndustrialRevolution/files/6756465/IR.1.zip)

**Comment by Czarniak4** [comment]
Here is my latest save before the update (it's my first time on GitHub so I'm not sure if it works).

**Comment by Deadlock989** [comment]
You have a metric buttload of unsupported stuff that could conflict in that save, like all the Bob's stuff, as well as a bunch of mods I've never heard of - it could be any of them causing this - too many mods for me to download.

All I can think of is that the dependency on Informatron was removed from IR in 2.2.1. That could change the mod loading order so that something is overwriting IR's change to the power pole fast replace groups and putting it back to the vanilla default., probably some mod just overwriting the whole prototype with its own slightly tweaked deal. Before the Informatron depdendency was removed IR was loading after this other mod, now IR is loading before it.

You can test this by copying the file `info.json` out of the IR mod zip file, opening it in a text editor, and changing this section:

```
   "dependencies": [  
	  "base >= 1.1.35",
	  "?DeadlockLargerLamp >= 1.5.0",
	  "(?)Dectorio",
	  "(?)textplates",
	  "(?)rso-mod"
   ],
```

to this:

```
   "dependencies": [  
	  "base >= 1.1.35",
	  "?DeadlockLargerLamp >= 1.5.0",
	  "?informatron",
	  "(?)Dectorio",
	  "(?)textplates",
	  "(?)rso-mod"
   ],
```

i.e. insert the line `"?informatron",` into the middle of the dependencies. If it loads after you make that change then it's a loading order thing.

To be honest I'm minded just to remove all the fast-replace / upgrade stuff from the big power poles, the upgrade planner is very needy and has been nothing but trouble.

**Comment by Czarniak4** [comment]
It worked, but it's strange as IR2 was the only mod I've updated today and before that everything was ok :/

**Comment by Deadlock989** [comment]
At least with the dependency tweak you can continue your save.

I will decide later what I want to do about this (if anything).

**Comment by Deadlock989** [comment]
I slept on it and decided to remove the fast replace group and next_upgrade path from big wooden poles and vanilla big electric poles. All that upgrade / fast replace stuff is too easily broken by mod conflicts.
