### ISSUE TITLE
Furnaces 3 can be researched when not all recipe prerequisites are met

### ISSUE THREAD

**Issue by Genhis** [Deadlock989/IndustrialRevolution#72]
Arc furnace recipe requires a junction box but doesn't depend on "Electric energy distribution 2" research which unlocks the junction box recipe.

Furnaces 3 tech is ignored by the regenerate process, so "Electric energy distribution 2" may need to be added manually as a prerequisite.

**Comment by Deadlock989** [comment]
Coincidentally I already addressed junction box issues for the next version - junction boxes recipe unlock will be moved back to Electronics 2, the same tech that unlocks the frame and the circuit - this eliminates a whole bunch of unnecessarily complex and/or broken dependencies because E2 is a prerequisite for purple science.

**Comment by Deadlock989** [comment]
Current patch notes re: dependecies FYI

```
    - Junction box recipe unlock moved to Electronics 2 to simplify several dependencies.
    - Modules 3 dependency removed from rocket control unit.
    - Rocket fuel dependency removed from rocket control unit, added to rocket silo.
```
