### ISSUE TITLE
ressource unreachable

### ISSUE THREAD

**Issue by Mabbe7** [Deadlock989/IndustrialRevolution#75]
In one world we can't make yellow potion to unlock the cubic pressor to unlock rubis, sapphir and diamond. So we need rubis to make laser assembler for one of the component of the yellow potion. (The blue ship).   We are block.  I use the minig depot mod but we can't get rubis we copper.  I check with FNEI and it said to use electric drill but its no use because we can only get copper or gold.

**Comment by Deadlock989** [comment]
Press I and read the page about mining and gems.

**Comment by Mabbe7** [comment]
I read it and I know that.  The problem is the gems are unlock and for that we need is some rubbies for the laser assembler for make one of the component  of the yellow potion. But we need yellow potion to unl;ock the cubic pressor and the gem.  The solution remove the cubic pressor from the yellow potion research and put it on the purple one.  By the way Im discussing with other players on the factorio discord and they having the same problem.  We trying to find a solution.

________________________________
De : Deadlock989 ***@***.***>
Envoyé : 21 juillet 2021 14:54
À : Deadlock989/IndustrialRevolution ***@***.***>
Cc : Mabbe7 ***@***.***>; Author ***@***.***>
Objet : Re: [Deadlock989/IndustrialRevolution] ressource unreachable (#75)


Press I and read the page about mining and gems.

**Comment by Genhis** [comment]
In small quantities, gems are present in other ores, you don't need a research to start mining them.

**Comment by rlundy** [comment]
@Mabbe7 It's perhaps a bit confusing about the gems if you haven't seen them before.  Not all mineral fields have them.  In particular, the fields close to your starting area don't have gems.  You'll have to explore further out in order to find gems.  You can get by without sapphires and diamonds for a while, but rubies are the really essential one.

On the map, you can see that an ore field has gems if it has tiny white diamond shapes sprinkled around the ore field.  On the ore field, you can hover a miner around the ore field and you'll see gems if there are any, because the miner will cover many points on the ore field at once.

It can be tricky to mine gems if they're in the midst of a bunch of enemy nests.  For my first rubies, I managed to lay a winding single track to the copper field I found that had rubies.  I used solar panels to power some miners, and a bunch of air filters with gold foil to clean all the pollution so the surrounding bugs never attacked.  Then it was just a matter of carting a bunch of ore back to the base to use up, while waiting for rubies.  I found it simplest to filter out the rubies and drop them in a box to be picked up later when there were a few of them.  I think I ended up needing only a small handful, maybe ten or so, to get me far enough to research the cubic press, after which I could make my own rubies, of course.
