### ISSUE TITLE
Shotgun can't use directional fire.

### ISSUE THREAD

**Issue by EarendelGames** [Deadlock989/IndustrialRevolution#76]
The generated prototypes for shotgun cartriges have a target type of "entity". This disables the ability to do directional fire with a shotgun. Shotgun type ammo usually has the target type set to "direction", which makes them more versatile. For someone used to vanilla shotgun combat, it makes the IR2 shotguns feel very clunky to use as sometimes they won't fire and sometimes they fire in an unexpected drection (at the nearest enemy insted of the aimed direction). 
https://wiki.factorio.com/Types/AmmoType#target_type

**Comment by Deadlock989** [comment]
It's been like that for almost 2 years, since the IR1 beta, and this has never come up. I haven't played vanilla Factorio since 0.16.

I can't reproduce the "firing in an unexpected direction" thing. In combat, I use both the "Shoot enemy" (shoot at entity nearest to cursor, Space key by default) and "Shoot selected" keys (shoot at a specific thing or location, C key by default) depending on the exact weapon behaviour I want. 

The "sometimes won't fire" might be due to the additional cartridge reload time which was deliberate and won't change. Vanilla doesn't put that property on the ammo tooltip, IR1 used to add additional localised descriptions that mocked up tooltip entries but I turned all of that off when the GUI updated for 0.18.

This feels like more of a personal preference thing than a "bug". However I'm not necessarily averse to changing it, I will compare both the target types again when I find the time. It may be that this was just a side effect of using the same function to generate both magazine and cartridge projectiles and I got used to it.

**Comment by Deadlock989** [comment]
So I reviewed this and took some time to check up on related things. Coincidentally the next update will mostly be updates to turrets so this was timely.

- I'm fine with the change for cartridges from "entity" to "direction", it doesn't really affect the way I play. Changed for next version.
- I reviewed the reload time penalty for cartridges and decided that it's just an annoyance. The property is never used in vanilla as far as I can see and there are several things about it that feel half-baked, run speed inconsistency being top of the list. Removed reload on cartridges for next version.
- Some gun and ammo properties were using a separate reference table that dates back to early IR1. In other places, the same or slightly different properties were being pulled from ammo component properties. I have reviewed all of that code and now all guns, ammo, combat robots and turrets get the same properties from the latter source and killed off the former. This fixes a couple of almost invisible things like autogun turret leading fire being very slightly out of sync with actual bullet speed etc.
