### ISSUE TITLE
Suggestion: Sorting/sorted transmat locations

### ISSUE THREAD

**Issue by matrixes** [Deadlock989/IndustrialRevolution#88]
Love the mod. The amount of effort and the balancing between added complexity without being overwhelming as well as the added graphical elements is impressive.

I do have a small pain point, and it's to do with the seemingly non-sorting order of transmat locations. Am I missing a setting somewhere or are the names not supposed to be sorted for some reason?

* Factorio: 1.1.48
* IR2-version: 2.3.2

Other mods

* Honk
* Squeak trough
* VehicleSnap
* YARM - Resource Monitor

**Comment by Deadlock989** [comment]
They _are_ sorted - but by their distance from the transmat you are currently operating, nearest first. (In fact it is a little more complex than that because it also accounts for off-world transmats if they are enabled, but as far as I know no third party mod is using those remote calls.)

There is no setting to change it. I am 99% sure there was a reason for doing it by distance instead of alphabetical order, but I have forgotten exactly what the reason was.

**Comment by matrixes** [comment]
Alright. At least it'll make _more_ sense to me from now on. :)
I'd personally have had a bit less of a brain bender had they been alphabetical, but since you already thought the sorting over with regards to this and I don't have anything substantial to add, we'll leave it at that.
